### ISSUE TITLE
Where do these .coverage.hostname.number.number files come from?

### ISSUE THREAD

**Issue by danijar** [pytest-dev/pytest-cov#100]
I cant remember changing anything but recently Pytest with Pytest-cov started creating a lot of file in the working directory in addition to the expected `.coverage` file.

```
.coverage.danijar-xps13-arch.18737.903083
.coverage.danijar-xps13-arch.19190.316378
.coverage.danijar-xps13-arch.19192.651456
.coverage.danijar-xps13-arch.19197.538345
.coverage.danijar-xps13-arch.19199.138180
.coverage.danijar-xps13-arch.19212.482496
.coverage.danijar-xps13-arch.19213.812768
.coverage.danijar-xps13-arch.19301.688885
...
```

Where do there files come from?

**Comment by ionelmc** [comment]
They appear if you use subprocesses or xdist.

**Comment by ionelmc** [comment]
They don't get removed at the end of the testrun?!

**Comment by danijar** [comment]
Ah, that's a useful bit of information. Yes, I use `subprocess` and on error, I `sys.exit()` so they probably cannot be cleaned up. Do you have an idea? Here is the [code inside setup.py](https://github.com/danijar/layered/blob/dc0e4f5a34be092dfe26c51adfd7888c64d672cf/setup.py#L29).

**Comment by ionelmc** [comment]
I mean, if you use subprocesses in your tests, then pytest-cov will automatically start measuring coverage in those processes (if they are python of course). That's what is making those files (besides using xdist).

**Comment by danijar** [comment]
Oh, I don't use subprocess in my tests, just in my setup.py to run pytest.

**Comment by ionelmc** [comment]
Does it reproduce without the setup.py shim?

**Comment by danijar** [comment]
Just tried that. The files are still there when I just run `python -m pytest --cov=layered test` or `py.test --cov=layered test`. Pytest version 2.8.5 and Pytest-cov version 2.2.0.

**Comment by ionelmc** [comment]
What's your coverage version?

**Comment by danijar** [comment]
Coverage is version 4.0.3. Pip says all of the three packages are up-to-date.

**Comment by ionelmc** [comment]
Is there a repository that reproduce the issue?

**Comment by danijar** [comment]
Yes, cloning danijar/layered and running `python3 setup.py test` reproduces the problem.

**Comment by iAnanich** [comment]
Have the same issue when using `asyncio` with `ProcessPoolExecutor`.

At the testing, it is a lot of `.coveage.<..>` files, but 2 of them always not get removed after tests complete.

`python 3.5.3`, `coverage==4.4.1 pytest==3.0.6 pytest-cov==2.5.1`

**Comment by ionelmc** [comment]
So I've looked at @danijar code and I bet @iAnanich has the same problem: unclean multiprocessing pool shutdown. You should have a `pool.join()` or similar before the test using the pool is done.

**Comment by danijar** [comment]
Thanks for looking into this!

**Comment by drorata** [comment]
I have a similar issue when testing a piece of code which uses [`GridSearchCV`](http://scikit-learn.org/stable/modules/generated/sklearn.model_selection.GridSearchCV.html). Under the hood, [`joblib.Parallel`](https://joblib.readthedocs.io/en/latest/generated/joblib.Parallel.html) is used and I guess/understand that it somehow messes up the files generated.

Any idea how to resolve this issue?
