### ISSUE TITLE
Add note to docs about pytest-cov and pytest doctest support

### ISSUE THREAD

**Issue by hangtwenty** [pytest-dev/pytest-cov#101]
A coworker of mine was shocked that the built-in pytest doctest support module didn't integrate with pytest-cov. He wrote a shim to get things working. I was shocked too: I am pretty sure  things already work, if you use the arguments in the right combination.

Seems like the gist is just to make sure you have "--doctest-modules" and "--cov" arguments, in your command (or config file).

like ...

```bash
py.test foo --cov=foo --doctest-modules
```

(*EDIT* -- my previous command example WORKED but it was misleading as to what was going on. command should now be more clear.*)

I think he was forgetting `--cov` argument and confusing himself. A hint in the docs might help folks avoid this blunder going forward.

So maybe it would be good to just include a usage example like the above, in some docs somewhere. When you look for "doctest" in the pytest-cov docs you don't find anything. Maybe this little FAQ or footnote should be stuffed somewhere, so that searching the pytest-cov docs for "doctest" brings up a hint.

Happy to make a PR... just unclear where to stick this.

**Comment by hangtwenty** [comment]
Could be related: https://github.com/pytest-dev/pytest-cov/issues/98

**Comment by ionelmc** [comment]
Hey. So having something like "pytest-cov will work with doctests if they are in docstrings and `--cov` (or coverage configuration) matches the containing module"?

**Comment by ionelmc** [comment]
I'm not sure how it even works (maybe pytest does some fancypants trickery to exec the code). We should have some tests, just in case.

**Comment by hangtwenty** [comment]
Yes, something quick like you mentioned ... maybe just a bit more detailed or search-able:

> pytest-cov will work with pytest's built-in [doctest support](https://pytest.org/latest/doctest.html). If you're having trouble, ensure the argument you pass to `--cov` matches the argument you pass to `--doctest-modules`. (Or, ensure the same idea, in your configuration files.) For example, if you have a module `foo` that contains your application code, and that code has some doctests, `py.test --doctest-modules=foo --cov=foo` will include coverage data from doctests in `foo` (as well as normal coverage data).

**Comment by hangtwenty** [comment]
As for fancypants trickery ...

The doctest support comes from the official/out-of-the-box plugin, `_pytest.doctest` ([docs](https://pytest.org/latest/plugins.html#pytest-default-plugin-reference)). Source code is [here](https://github.com/pytest-dev/pytest/blob/master/_pytest/doctest.py). Assuming there's fine coverage of the doctest module, upstream ... I'm not sure we need to add unit tests before adding this little tip to the docs (but I'm all ears)

**Comment by hangtwenty** [comment]
@ionelmc given my last comment/two ... do you think we need to add unit tests before adding the tip to the documentation -- or can we just go ahead and add the tip?

**Comment by ionelmc** [comment]
Go ahead and change the docs. I'll take a look at the test part.

**Comment by ionelmc** [comment]
Oooops, looks like I was wrong. Sorry for making you do the PR. I did some local tests, docstrings are always going to appear as "covered". Doctests are in docstrings so they always get 100% coverage.

Eg, try this and you'll see coverage is 100% which is wrong:

```diff
diff --git a/tests/test_pytest_cov.py b/tests/test_pytest_cov.py
index 0e2f21d..0beb84f 100644
--- a/tests/test_pytest_cov.py
+++ b/tests/test_pytest_cov.py
@@ -154,6 +154,35 @@ def test_central(testdir):
     assert result.ret == 0


+def test_doctest(testdir):
+    script = testdir.makepyfile('''
+def foo():
+    """
+    Doctest::
+
+        >>> a = 1
+        >>> a + 1
+        2
+        >>> if 0:
+        ...     a + b
+
+
+    """
+''')
+
+    result = testdir.runpytest('-v',
+                               '--cov=%s' % script.dirpath(),
+                               '--cov-report=term-missing',
+                               '--doctest-modules',
+                               script)
+
+    result.stdout.fnmatch_lines([
+        '*- coverage: platform *, python * -*',
+        'test_central* 123 *',
+    ])
+    assert result.ret == 0
+
+
 def test_annotate(testdir):
     script = testdir.makepyfile(SCRIPT)

```
