### ISSUE TITLE
Using cov results in different behaviour of tested code

### ISSUE THREAD

**Issue by xaedes** [pytest-dev/pytest-cov#104]
I have some pygame code that I want to test with py.test. Using "--cov" will alter the output of pygame drawing functions resulting in failed tests.
### minimal failing example

https://github.com/xaedes/pytest-cov-pygame-bug

readme.md:

```
Testing this code with "py.test" will pass.
Testing this code with "py.test --cov=." will NOT pass.

The tested code draws an antialiased line using pygame.

It should look like 'image.png'. But using "--cov=." will result in 'image_test.png'
```
### System information:

python --version

```
Python 2.7.11
```

**On my other machine with Python 2.7.6 it won't happen.**

lsb_release -a

```
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu Xenial Xerus (development branch)
Release:        16.04
Codename:       xenial
```

uname -a

```
Linux xaedes-vbox 4.3.0-2-generic #11-Ubuntu SMP Fri Dec 4 20:37:48 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

py.test --version

```
This is pytest version 2.8.5, imported from /usr/local/lib/python2.7/dist-packages/pytest.pyc
setuptools registered plugins:
  pytest-cov-2.2.0 at /usr/local/lib/python2.7/dist-packages/pytest_cov/plugin.pyc
  pytest-mock-0.9.0 at /usr/local/lib/python2.7/dist-packages/pytest_mock.pyc
```

python: pygame.version.ver

```
'1.9.1release'
```

**Comment by xaedes** [comment]
On yet another machine with Python 2.7.10 it also won't happen.

**Comment by ionelmc** [comment]
How does the assertion failure look?

**Comment by ionelmc** [comment]
Nevermind, it's in the repo.

**Comment by ionelmc** [comment]
@xaedes does the problem reproduce with just coverage? eg: `coverage run -mpytest ...`

**Comment by ionelmc** [comment]
> On yet another machine with Python 2.7.10 it also won't happen.

You mean that the problem reproduces there too or that it doesn't?

**Comment by xaedes** [comment]
Yes, it does reproduce with coverage:

    xaedes@xaedes-vbox: ~/gits/pytestbug$ coverage run -m pytest
    ================================================================================================ test session starts ================================================================================================
    platform linux2 -- Python 2.7.11, pytest-2.8.5, py-1.4.31, pluggy-0.3.1
    rootdir: /home/xaedes/gits/pytestbug, inifile: 
    plugins: cov-2.2.0, mock-0.9.0
    collected 1 items 

    test_draw.py F

    ===================================================================================================== FAILURES ======================================================================================================
    _____________________________________________________________________________________________________ test_draw _____________________________________________________________________________________________________

        def test_draw():
            screen = draw()
            reference = pygame.image.load("image.png")
        
            pygame.image.save(screen, "image_test.png")
        
            np.testing.assert_almost_equal(
                pygame.surfarray.pixels3d(screen),
    >           pygame.surfarray.pixels3d(reference)
                )
    E       AssertionError: 
    E       Arrays are not almost equal to 7 decimals
    E       
    E       (mismatch 2.625%)
    E        x: array([[[255, 255, 255],
    E               [255, 255, 255],
    E               [255, 255, 255],...
    E        y: array([[[255, 255, 255],
    E               [255, 255, 255],
    E               [255, 255, 255],...

    test_draw.py:17: AssertionError
    ============================================================================================= 1 failed in 0.20 seconds ==============================================================================================

**Comment by xaedes** [comment]
Sorry, that wasn't very clear. On the Python 2.7.10 machine the problem **does not** reproduce.

**Comment by ionelmc** [comment]
Worth reporting a `coverage` bug at https://bitbucket.org/ned/coveragepy

`pytest-cov` don't implement any tracer, it just does some fancy pants wrapping for `coverage`.

**Comment by xaedes** [comment]
Ok, thank you for your fast answers!
I just reported it on the coverage repo.

For reference:
https://bitbucket.org/ned/coveragepy/issues/463/using-coverage-run-results-in-different

**Comment by Zac-HD** [comment]
Fixed upstream: https://github.com/nedbat/coveragepy/issues/463
