### ISSUE TITLE
Unhandled `AttributeError` on interpreter teardown.

### ISSUE THREAD

**Issue by kwlzn** [pytest-dev/pytest-cov#107]
as seen in the wild by one of our users when running tests via `pants`->`pytest`->`pytest-cov` (cov_core==1.15.0):

```
Traceback (most recent call last):
  File "/opt/twitter_mde/package/python2.7/current/lib/python2.7/multiprocessing/util.py", line 274, in _run_finalizers
    finalizer()
  File "/opt/twitter_mde/package/python2.7/current/lib/python2.7/multiprocessing/util.py", line 207, in __call__
    res = self._callback(*self._args, **self._kwargs)
  File "/Users/$USER/workspace/source/.pants.d/python-setup/chroots/1e3885db69246b4c848a434fedb4b7938a5f4793/.deps/cov_core-1.15.0-py2-none-any.whl/cov_core.py", line 19, in multiprocessing_finish
    cov.stop()
AttributeError: 'NoneType' object has no attribute 'stop'
```

it appears the finalizer at https://github.com/pytest-dev/pytest-cov/blob/master/src/pytest_cov/embed.py#L25 expects the `cov` object to always be available at execution time, which is not always the case during interpreter teardown. it's best to guard against this in finalizers and atexit handlers etc - a simple try/catch->pass should suffice.

**Comment by schlamar** [comment]
This should already be handled in newer versions of pytest-cov (https://github.com/pytest-dev/pytest-cov/blob/master/src/pytest_cov/embed.py#L21). Please note that cov_core is embedded in pytest-cov for a while now, so you are using a pretty old version.

**Comment by kwlzn** [comment]
ah - did not realize we were that out of date and the commit history for `embed.py` isn't particularly helpful in illustrating the lineage of that code path. I'll take a look at upgrading to the latest release and reopen should this happen again. thanks.

**Comment by peiyuwang** [comment]
I still see this happening, after upgraded to the newer `pytest-cov` exceptions went away.

```
diff --git a/3rdparty/python/requirements.txt b/3rdparty/python/requirements.txt
index ac89c78..a903c69 100644
--- a/3rdparty/python/requirements.txt
+++ b/3rdparty/python/requirements.txt
@@ -1,6 +1,6 @@
 ansicolors==1.0.2
 beautifulsoup4>=4.3.2,<4.4
-coverage>=3.7,<3.8
+coverage>=3.7.1,<3.8
 docutils>=0.12,<0.13
 fasteners==0.14.1
 futures==3.0.5
@@ -15,7 +15,7 @@ psutil==3.1.1
 pyflakes==1.1.0
 Pygments==1.4
 pystache==0.5.3
-pytest-cov>=1.8,<1.9
+pytest-cov==2.2.1
 pytest>=2.6,<2.7
 pywatchman==1.3.0
 requests>=2.5.0,<2.6
```

Will send out a review.
