### ISSUE TITLE
Incorrect coverage report

### ISSUE THREAD

**Issue by jgosmann** [pytest-dev/pytest-cov#117]
Using `py.test --cov-config .coveragerc --cov nengo -n 6  nengo` a lot of lines that should be hit get reported as missed (like class and function definitions in a module). This might be related to #19 as the project has a conftest file importing other modules from the project.

Using `coverage run --rcfile .coveragerc --source nengo -m py.test nengo` instead a correct coverage report is generated, but this command does not support xdist.

**Comment by ionelmc** [comment]
It might be possible to measure it with a workaround like this: https://github.com/ionelmc/pytest-benchmark/blob/master/tox.ini#L32-L33 - it forces the engine used for subprocess measurements to load early.

**Comment by yunstanford** [comment]
Have this been fixed ? i am still getting this issue.

**Comment by ionelmc** [comment]
Not yet fixed. There is a workaroud tho.

**Comment by yunstanford** [comment]
hmm.. i just curious why it works in Mac but doesn't work on linux..

**Comment by ionelmc** [comment]
Show an example and maybe we can figure it out.

**Comment by yunstanford** [comment]
I used it with https://github.com/yunstanford/pytest-sanic, when i ran `pytest` locally, the coverage looks correct to me. but it doesn't look right in remote host.

**Comment by yunstanford** [comment]
you can checkout the last travis ci build of Sanic https://github.com/channelcat/sanic

**Comment by ionelmc** [comment]
Maybe your local checkout is dirty (have any `.coverage`/`.coverage.*` files?). Can we narrow it down to something smaller?

**Comment by ionelmc** [comment]
Ah yes, it's a pytest plugin, so plugin loading is currently unpredictable. See https://github.com/pytest-dev/pytest/issues/935

**Comment by yunstanford** [comment]
yeah, you're right. i had `.coverage` files, after `git clean -xfd`, i can also reproduce locally.

**Comment by yunstanford** [comment]
How can we fixed that ? should we load `pytest-cov` first ? what step matters actually when running pytest, `pytest_configure` ?

**Comment by ionelmc** [comment]
Well ... this being a problem in pytest, we can only talk about workarounds here.

**Comment by yunstanford** [comment]
yeah, any suggestion ? it works fine for me when i use `uranium` another python build system. but it doesn't work with `tox`.

**Comment by ionelmc** [comment]
Afaik it's either the workaround I use in pytest-benchmark (forceload pytest-cov subprocess engine) or ronny's plugin trick (haven't tried it).

**Comment by yunstanford** [comment]
https://github.com/ionelmc/pytest-benchmark/blob/master/tox.ini#L52-L53 ?

**Comment by ionelmc** [comment]
Ah ... now I get the confusion, line numbers changed: https://github.com/ionelmc/pytest-benchmark/blob/51b3bf7ebf85bfd73445446e167a9a89171582d6/tox.ini#L25-L27

**Comment by yunstanford** [comment]
hmm.. it doesn't work for me by just setting these env.. am i missing anything ?

**Comment by ionelmc** [comment]
What happens if you run
```
coverage combine --append
coverage report
```

**Comment by yunstanford** [comment]
Then looks correct.

**Comment by yunstanford** [comment]
yeah, but `pytest` always prints out the `incorrect` one first. is there any way to disable that ?

**Comment by yunstanford** [comment]
nvm, `--cov-report=`

**Comment by ionelmc** [comment]
This is fixed right? Also, #177 will clarify the solutions.
