### ISSUE TITLE
v2.3.0 Release Date?

### ISSUE THREAD

**Issue by Kuwagata** [pytest-dev/pytest-cov#121]
Hello!  I was wondering if there's a release date planned for `v2.3.0`.  I would love to get the fix from #116 without having to pull master in my `requirements.txt`.

**Comment by ionelmc** [comment]
Ah woops, I forgot to make release. Here it is: https://pypi.python.org/pypi/pytest-cov/2.3.0

**Comment by Kuwagata** [comment]
@ionelmc Wow, that was fast.  Thanks!
