### ISSUE TITLE
coverage doesn't work after upgrade to pytest-cov 2.3.0

### ISSUE THREAD

**Issue by kmike** [pytest-dev/pytest-cov#123]
Hi,

Scrapy testing suite starts to fail with `"ERROR: Failed to generate report: No data to report."` error message after upgrading to pytest-cov 2.3.0. With pytest-cov 2.2.1 it works (see https://github.com/scrapy/scrapy/pull/2095).

**Comment by ionelmc** [comment]
Hmmm not sure but this makes it go away:
```diff
diff --git a/.coveragerc b/.coveragerc
index 3105409..ee96d64 100644
--- a/.coveragerc
+++ b/.coveragerc
@@ -1,6 +1,6 @@
 [run]
 branch = true
-include = scrapy/*
+include = */scrapy/*
 omit =
   tests/*
   scrapy/xlib/*
```

**Comment by ionelmc** [comment]
It's not clear to me why you're using the `include` option while you specify the sources directly (via `--cov=scrapy`). That also means not using the `include` option makes the problem go away.

As to what caused the problem - likely candidate is https://github.com/pytest-dev/pytest-cov/compare/v2.2.1...v2.3.0#diff-3db14ea221c08dabe6d00f457c4cabbeL38 - but that would only affect subprocess measurements. Are you running the tests in subprocesses? (I'm not sure how the twisted plugin works)

**Comment by kmike** [comment]
@ionelmc thanks for looking at it! Yes, some tests are executed in subprocesses (we're testing CLI utilities this way); I think `pytest-twisted` doesn't use subprocess, but not 100% sure.

Using `*/scrapy/*` indeed makes it pass, though the same change should be made to all `omit` lines.

**Comment by ionelmc** [comment]
@kmike does your suite do any CWD changes?

PS. there's gonna be a 2.3.1 release soon ... hope to sort this out as well.

**Comment by kmike** [comment]
@ionelmc it seems the answer is yes: https://github.com/scrapy/scrapy/search?utf8=%E2%9C%93&q=chdir. I'll check it again after 2.3.1 release, thanks!

**Comment by ionelmc** [comment]
Not sure I can fix this. The change in https://github.com/pytest-dev/pytest-cov/compare/v2.2.1...v2.3.0#diff-3db14ea221c08dabe6d00f457c4cabbeL38 exists for a very specific reason: it allow people with broken layouts (non-src) to collect coverage for the files installed in site-packages (as opposed to checkout dir).

Perhaps this is a coverage issue (incorrect handling of non-path source) - what do you think @nedbat?

**Comment by istinspring** [comment]
Got same problem, 

removal of from `.coveragerc`

```text
source = 
        *.py
```

made it works again.

**Comment by ionelmc** [comment]
Closing in favour of #176 .
