### ISSUE TITLE
pytest-cov does not read settings from setup.cfg

### ISSUE THREAD

**Issue by urbaniak** [pytest-dev/pytest-cov#126]
When running coverage from py.test it does not pick up the settings from `setup.cfg`'s section `[coverage:run]`, other py.test settings are working fine from `setup.cfg`.

After copying that section to `.coverragerc` as `[run]` it worked fine.

I'm sure it's not picking up the settings cause it reports coverage for files specified in omit.

Here are version:
```
platform darwin -- Python 3.5.2, pytest-2.9.2, py-1.4.31, pluggy-0.3.1
django settings: seven_bridges.settings.local (from ini file)
rootdir: /Users/urban/Development/7bridges/seven_bridges, inifile: setup.cfg
plugins: cov-2.3.0, django-2.9.1, env-0.6.0, flake8-0.5, flakes-1.0.1, isort-0.1.0, pep8-1.0.6
```

**Comment by zakuro9715** [comment]
hmm... I tried but It seems to work.

- `--cov-config` value is `.coverage` by default. (https://github.com/pytest-dev/pytest-cov/blob/6d119317951e8d8313b6ca25a5ca98b105306f2b/src/pytest_cov/plugin.py#L65).
- Then pytest_cov pass it to coverage as config_file. (https://github.com/pytest-dev/pytest-cov/blob/6d119317951e8d8313b6ca25a5ca98b105306f2b/src/pytest_cov/engine.py#L136-L137)
- coverage uses 'setup.cfg' when config_file is '.coveragerc' and faild to read it. (https://bitbucket.org/ned/coveragepy/src/31c45d77cafdff68b6d160cc2e45bd1aee3d9423/coverage/control.py?at=default&fileviewer=file-view-default#control.py-129:147

Please put here if you have any examples.

**Comment by urbaniak** [comment]
Got empty .coveragerc, thats probably why it didn't read the setup.cfg, thanks! Closing it now.

**Comment by jothiram-eb** [comment]
@urbaniak how did you solve this issue? did you just delete the .coveragerc file?
