### ISSUE TITLE
Misleading help message for source

### ISSUE THREAD

**Issue by minddust** [pytest-dev/pytest-cov#133]
While switching from plain coverage to pytest-cov I noticed that the *multiple sources* option isn't really supported because `nargs` is set to `?`. Any thoughts about this?

Related [plugin.py (line 54-57)](https://github.com/pytest-dev/pytest-cov/blob/master/src/pytest_cov/plugin.py#L54-L57) code:

``` python
    group.addoption('--cov', action='append', default=[], metavar='path',
                    nargs='?', const=True, dest='cov_source',
                    help='measure coverage for filesystem path '
                    '(multi-allowed)')
```

Related covery.py docs: http://coverage.readthedocs.io/en/latest/source.html

**Comment by ionelmc** [comment]
Note the `action='append'`.

**Comment by minddust** [comment]
works. maybe i was too tired to see the obvious. 😴 

thanks!
