### ISSUE TITLE
No data was collected. Incorrect stats if tox is used

### ISSUE THREAD

**Issue by ivankravets** [pytest-dev/pytest-cov#134]
Please take a look at this stats: https://travis-ci.org/platformio/platformio/jobs/160557892#L484

I'm not sure that this issue related with `pytest-cov`, maybe with `coverage`. Nevertheless, it worked before. See https://codecov.io/gh/platformio/platformio

Config: https://github.com/platformio/platformio/blob/develop/tox.ini#L64

Thanks a lot for this plugin!

**Comment by ryanhiebert** [comment]
There's not a lot to go on with this issue report, but since this seems to have to do with Tox, this might perhaps be related to #130, or to the potential fix I've proposed in #142. @ivankravets : would you be willing to try out the patch I've proposed in #142, and see if it works for you?

**Comment by astronouth7303** [comment]
I'm getting a similar error in [xonsh/slug](https://github.com/xonsh/slug) across Travis, Appveyor, and CircleCI. Only CircleCI uses tox. All of them produce no coverage. Running the same command locally does produce coverage. Running locally under tox does _not_ produce coverage.

Is there a necessary envvar missing or something?

**Comment by ionelmc** [comment]
@astronouth7303 you have an unrelated issue there, it's more like https://github.com/pytest-dev/pytest-cov/issues/98 - shortest fix for you is to use this feature of coverage: https://coverage.readthedocs.io/en/coverage-4.3.4/config.html#paths

**Comment by astronouth7303** [comment]
The coverage XML produced lists the files, but has no coverage--everything has 0 hits.

**Comment by ionelmc** [comment]
@astronouth7303 yes, but try removing the filters (eg: use bare `--cov`, not `--cov=something`) to see if you really have empty coverage.

**Comment by astronouth7303** [comment]
Same files, all with `hits="0"`.

**Comment by astronouth7303** [comment]
Also, it says "Coverage.py warning: No data was collected."

**Comment by ionelmc** [comment]
@astronouth7303 maybe it's the source filter in your `.coveragerc`?

**Comment by astronouth7303** [comment]
Deleted `.coveragerc`. The warning is no longer being printed, but the `coverage.xml` still has no hits.

**Comment by ionelmc** [comment]
Not sure what you're doing there bit it seems to be working as expected, eg:

```
.tox/py35/lib/python3.5/site-packages/slug/__init__.py                         14      4    71%
.tox/py35/lib/python3.5/site-packages/slug/base.py                             71     24    66%
.tox/py35/lib/python3.5/site-packages/slug/posix.py                             0      0   100%
.tox/py35/lib/python3.5/site-packages/slug/utils.py                             0      0   100%
```

Here are the changes: 
```diff
diff --git a/.coveragerc b/.coveragerc
deleted file mode 100644
index 748554f..0000000
--- a/.coveragerc
+++ /dev/null
@@ -1,4 +0,0 @@
-[run]
-branch = true
-source =
-  slug/
diff --git a/tox.ini b/tox.ini
index 43efc21..b015bc5 100644
--- a/tox.ini
+++ b/tox.ini
@@ -8,5 +8,5 @@ passenv =
   CIRCLECI
   CIRCLE_*
 commands=
-  py.test --flake8 --timeout=10 --cov=./slug --cov-report=xml:coverage.xml
+  py.test --flake8 --timeout=10 --cov --cov-report=term
   codecov -X gcov
```

Unfortunately there's nothing that pytest-cov can do about this. This is a problem created by the combination of coverage's legacy handling of filters (it mixes up paths with module names in configuration) and problematic package layout (see [1](https://hynek.me/articles/testing-packaging/) and [2](http://blog.ionelmc.ro/2014/05/25/python-packaging/)).

IOW, you cannot filter by module if there's a directory with same name in CWD - sadly that's just how coverage works. Other workarounds (besides fixing the layout) could be:

* changing cwd during test run (not sure if this really works)
* remove filters (as in diff) and filter and fix paths with subsequent `coverage combine` commands (or contraption of that sort)
* use development installs (https://tox.readthedocs.io/en/latest/config.html#confval-usedevelop=BOOL) - note that this has some pitfalls (you're not testing what users will actually install)

**Comment by astronouth7303** [comment]
Ah, apparently you need `--cov` (which I really should have known in retrospect). I'll save figuring out for filters another day.

**Comment by ionelmc** [comment]
This is sorted out right?
