### ISSUE TITLE
running --cov on submodule?

### ISSUE THREAD

**Issue by goanpeca** [pytest-dev/pytest-cov#137]
is it normal that running 

`pytest --cov=top_module` works but

`pytest --cov=top_module/submodule` does not?

**Comment by ionelmc** [comment]
Sounds like normal behavior (first one being a module name and second one being a path that doesn't exist - thus no coverage).

**Comment by goanpeca** [comment]
the secon path does exist but there is no coverage at all and

**Comment by ionelmc** [comment]
I mean it doesn't exist in the coverage data. Perhaps you want to use a development install (so it's not installed site-packages?) or `--cov=topmodule.submodule`.
