### ISSUE TITLE
Allow overriding of data file location

### ISSUE THREAD

**Issue by jezdez** [pytest-dev/pytest-cov#145]
For various reasons it'd be useful to be able to specify the location of the data file.

The path to the file was hard-coded in a14e746d1bbb89763a3c1717d3fc4f6f394a2449 which makes sense to fix the issue for sub-processes, but some environments don't allow writing to the CWD (certain Docker setups).

**Comment by ionelmc** [comment]
We could have an `--cov-datapath` option, or something to that effect.

Just out of curiosity, do you have an example of a project that is using a readonly mount in cwd?

**Comment by jezdez** [comment]
@ionelmc That sounds what I was looking for.

I don't have an easy to reproduce example at the moment, but the general gist is that we're trying to run tests in a Docker container with a command that is running as a non-privileged user and which has the app code (the host's CWD) mounted as a volume. The restrictions of Docker's volume implementation basically makes any volume owned by root inside the container. I realize that this is an edge case, but since coverage.py allows setting the data file as well and I don't see a reason for this to be hardcoded in pytest-cov I hoped this would be an easy fix®.

**Comment by ionelmc** [comment]
@jezdez is putting `[run] data_file=/tmpsomething/.coverage` in your coverage config not an option? For docker the path doesn't need to be very dynamic (you can mount wherever you want), thus it can sit just fine in a configuration file.

**Comment by jezdez** [comment]
@ionelmc That's what I tried first but then found the plugin to [pass in a value manually](https://github.com/pytest-dev/pytest-cov/blob/baf85809460428dbb09883711892f491ddfd927e/src/pytest_cov/embed.py#L65) which prevented it from working. I can check again, but I think it's safe to say that this is hardcoding `.coverage` [right now](https://github.com/pytest-dev/pytest-cov/blob/baf85809460428dbb09883711892f491ddfd927e/src/pytest_cov/engine.py#L43).

**Comment by ionelmc** [comment]
Aaah, now I understand the actual problem: we don't take the datafile path from the coverage object - we just guess it with abspath('.coverage').

**Comment by jezdez** [comment]
@ionelmc Yep, apologies for not stating it more clearly at first.

**Comment by ionelmc** [comment]
Released `2.5.1`.
