### ISSUE TITLE
Send '.coverage' docker output to coveralls from travis

### ISSUE THREAD

**Issue by jeff1evesque** [pytest-dev/pytest-cov#146]
The pytest-cov [documentation](http://pytest-cov.readthedocs.io/en/latest/readme.html#reporting) states the following:

>These three report options output to files without showing anything on the terminal:
>
>```python
>    py.test --cov-report html
>            --cov-report xml
>            --cov-report annotate
>            --cov=myproj tests/
>```
>
>The output location for each of these reports can be specified. The output location for the XML report is
>a file. Where as the output location for the HTML and annotated source code reports are directories:
>
>```python
>py.test --cov-report html:cov_html
>         --cov-report xml:cov.xml
>         --cov-report annotate:cov_annotate
>         --cov=myproj tests/
>```
>
>The final report option can also suppress printing to the terminal:
>
>```python
>py.test --cov-report= --cov=myproj tests/
>```
>
>This mode can be especially useful on continuous integration servers, where a coverage file is needed 
>for subsequent processing, but no local report needs to be viewed. For example, tests run on Travis-CI 
>could produce a .coverage file for use with Coveralls.

But, how do I send the redirected report generated from `--cov-report`, to coveralls?  I am currently using this framework within a series of docker containers, which my `.travis.yml` spins up for unit testing.  This framework generates the coverage report, and copied from a docker container, to the host for the Travis CI.  Then, my implementation of [python-coveralls](https://github.com/z4r/python-coveralls/issues/59), used explicitly by Travis is responsible for sending the coverage report to coveralls:

```python
        pytest.main([
            '--cov', '.',
            '--cov-report', 'xml:/var/machine-learning/coverage.xml',
            'test/live_server'
        ])
```

However, it seems the xml option is an [invalid format](https://travis-ci.org/jeff1evesque/machine-learning/builds/192214255#L6751-L6763) for sending to coveralls.

**Note:** this is the associated [issue](https://github.com/jeff1evesque/machine-learning/issues/2697) I'm working on corresponding to the above statement.

**Comment by ionelmc** [comment]
https://pypi.python.org/pypi/coveralls works by reading the datafiles (those `.coverage` files) - nothing else needed (ok, maybe a `coverage combine` if you have multiple datafiles).

**Comment by jeff1evesque** [comment]
Hi @ionelmc, how do I generate the `.coverage` file, from the following implementation:

```python
    py.test --cov-report html
            --cov-report xml
            --cov-report annotate
            --cov=myproj tests/
```

**Comment by ionelmc** [comment]
It's already there. PS. The reporting steps are unnecessary.

**Comment by jeff1evesque** [comment]
Will running `(cd /var/some/directory && py.test --cov . test/live_server`, generate `/var/some/directory/.coverage`?

**Comment by ionelmc** [comment]
Yes.

**Comment by jeff1evesque** [comment]
@ionelmc, you're right.  I [removed](https://github.com/jeff1evesque/machine-learning/commit/d53db584bdbe1265d4f5dbe816b50fd7b35906b8) `--cov-report`:

```python
        pytest.main([
            '--cov', '.',
            'test/live_server'
])
```

Then, I attempted to ensure `coveralls --data_file=.coverage` within my [`.travis.yml`](https://github.com/jeff1evesque/machine-learning/blob/f2d09163eef6dac7ff87f80c479db8fc9c05c514/.travis.yml#L130-L131), which generated the following traceback:

>The command "docker ps -a" exited with 0.
>
>0.16s$ coveralls --data_file=.coverage
>
>Traceback (most recent call last):
>
>  File "/home/travis/virtualenv/python2.7.12/bin/coveralls", line 11, in <module>
>
>    sys.exit(wear())
>
>  File "/home/travis/virtualenv/python2.7.12/lib/python2.7/site-packages/coveralls/__init__.py", line 94, 
>in wear
>
>    source_files=coverage.coveralls(args.base_dir, ignore_errors=args.ignore_errors, 
>merge_file=args.merge_file),
>
>  File "/home/travis/virtualenv/python2.7.12/lib/python2.7/site-packages/coveralls/control.py", line 9, in 
>coveralls
>
>    return reporter.report(base_dir, ignore_errors=ignore_errors, merge_file=merge_file)
>
>  File "/home/travis/virtualenv/python2.7.12/lib/python2.7/site-packages/coveralls/report.py", line 15, in 
>report
>
>    with open(fr.filename) as fp:
>
>IOError: [Errno 2] No such file or directory: u'/var/machine-learning/__init__.py'

Is there a better syntax you could recommend for the `after_success:` directive within the [`.travis.yml`](https://github.com/jeff1evesque/machine-learning/blob/f2d09163eef6dac7ff87f80c479db8fc9c05c514/.travis.yml#L130-L131), to ensure my [coveralls](https://coveralls.io/github/jeff1evesque/machine-learning) properly receives the corresponding coverage report?

**Comment by ionelmc** [comment]
It appears that coveralls is attempting to read your sourcefiles. Don't know why but you can fix your data file to have the right paths inside by running `coverage combine` with [adequate coverage configuration](https://coverage.readthedocs.io/en/coverage-4.3.1/config.html#paths). 

Suggested conf, YMMV:
```
[paths]
source =
    /var/machine-learning
    .
```

**Comment by jeff1evesque** [comment]
I added the [`.coveragerc`](https://github.com/jeff1evesque/machine-learning/blob/e9d894af51537fd2c6cb248fc40cdc3854181ab5/.coveragerc) file, then made a reference, when running the `coveralls` command within my [`travis.yml`](https://github.com/jeff1evesque/machine-learning/blob/5f7da8edcd916c47a9f5ebfa850fe684128beaa9/.travis.yml#L131).  However, I'm still getting a similar traceback:

>$ coveralls --data_file=.coverage --config_file=.coveragerc
>
>Traceback (most recent call last):
>
>  File "/home/travis/virtualenv/python2.7.12/bin/coveralls", line 11, in <module>
>
>    sys.exit(wear())
>
>  File "/home/travis/virtualenv/python2.7.12/lib/python2.7/site-packages/coveralls/__init__.py", line 94, 
>in wear
>
>    source_files=coverage.coveralls(args.base_dir, ignore_errors=args.ignore_errors, 
>merge_file=args.merge_file),
>
>  File "/home/travis/virtualenv/python2.7.12/lib/python2.7/site-packages/coveralls/control.py", line 9, in 
>coveralls
>
>    return reporter.report(base_dir, ignore_errors=ignore_errors, merge_file=merge_file)
>
>  File "/home/travis/virtualenv/python2.7.12/lib/python2.7/site-packages/coveralls/report.py", line 15, in 
>report
>
>    with open(fr.filename) as fp:
>
>IOError: [Errno 2] No such file or directory: u'/var/machine-learning/__init__.py'

I guess I have forgotten to run the `combine` command.  Should I still implement that, and should that be done in conjunction with pytest-cov, or with `coveralls` within the `.travis.yml`?

**Comment by jeff1evesque** [comment]
Since the coverage is run from the docker container (which travis spins up), then the corresponding report returned to [`.travis.yml`](https://github.com/jeff1evesque/machine-learning/blob/5f7da8edcd916c47a9f5ebfa850fe684128beaa9/.travis.yml#L118), I never run `coverage`, or any coveralls command within the `script` directive of my `.travis.yml`.

**Comment by ionelmc** [comment]
If you have the `coveralls` bin then you'll also have the `coverage` bin.

**Comment by jeff1evesque** [comment]
Hi @ionelmc, I'm not sure what you mean by:

>If you have the `coveralls` bin then you'll also have the `coverage` bin.

Reading more of the `coveralls` [documentation](https://coverage.readthedocs.io/en/coverage-4.3.1/config.html#paths):

>The first value must be an actual file path on the machine where the reporting will happen, so that source 
>code can be found. The other values can be file patterns to match against the paths of collected data, or 
>they can be absolute or relative file paths on the current machine.

So, I made some minor changes to my [`.coveragerc`](https://github.com/jeff1evesque/machine-learning/commit/dc72d6c8683e811f4772801963ca33a045032d54) file, since I interpreted the travis directory, as being the file path where the reporting is done, even though the report was generated in docker, and copied into travis.  Am I missing anything under my `script` directive in the `.travis.yml`, or should I adjust the `coveralls` command in the `after_success`?  I'm still unsure how to provide the generated `.coverage` report to coveralls

**Comment by jeff1evesque** [comment]
I'm still getting the following traceback:

>$ coverage combine --append
>
>no such option: --append
>
>Use 'coverage help' for help.
>
>after_success.2
>
>0.22s$ coveralls
>
>Traceback (most recent call last):
>
>  File "/home/travis/virtualenv/python2.7.12/bin/coveralls", line 11, in <module>
>
>    sys.exit(wear())
>
>  File "/home/travis/virtualenv/python2.7.12/lib/python2.7/site-packages/coveralls/__init__.py", line 94, 
>in wear
>
>    source_files=coverage.coveralls(args.base_dir, ignore_errors=args.ignore_errors, >merge_file=args.merge_file),
>
>  File "/home/travis/virtualenv/python2.7.12/lib/python2.7/site-packages/coveralls/control.py", line 9, in 
>coveralls
>
>    return reporter.report(base_dir, ignore_errors=ignore_errors, merge_file=merge_file)
>
>  File "/home/travis/virtualenv/python2.7.12/lib/python2.7/site-packages/coveralls/report.py", line 15, in 
>report
>
>    with open(fr.filename) as fp:
>
>IOError: [Errno 2] No such file or directory: u'/var/machine-learning/__init__.py'

I'm going to determine what commands are available via `coverage help`.  But, even if there is an alternative syntax to `coverage combine --append`, I'm worried that I will have similar results when running the `coveralls` command within the `after_success` directive.

**Comment by jeff1evesque** [comment]
Sorry, changed the title to better reflect the issue in one line.

**Comment by ionelmc** [comment]
The `--append` option was introduced in 4.2, and you have 4.0.3 in that build.

**Comment by ionelmc** [comment]
IOW: either remove `--append` or upgrade to >=4.2

**Comment by jeff1evesque** [comment]
Do I still need my earlier [`.coveragerc`](https://github.com/jeff1evesque/machine-learning/commit/dc72d6c8683e811f4772801963ca33a045032d54), because I recently removed it, before adding your [recent suggestion](https://github.com/pytest-dev/pytest-cov/issues/146#issuecomment-272934047) (removing `--append`).  However, the travis ci is still complaining, after pushing both changes:

>$ coverage combine
>
>after_success.2
>
>0.16s$ coveralls
>
>Traceback (most recent call last):
>
>  File "/home/travis/virtualenv/python2.7.12/bin/coveralls", line 11, in <module>
>
>    sys.exit(wear())
>
>  File "/home/travis/virtualenv/python2.7.12/lib/python2.7/site-packages/coveralls/__init__.py", line 94, 
>in wear
>
>    source_files=coverage.coveralls(args.base_dir, ignore_errors=args.ignore_errors, 
>merge_file=args.merge_file),
>
>  File "/home/travis/virtualenv/python2.7.12/lib/python2.7/site-packages/coveralls/control.py", line 9, in 
>coveralls
>
>    return reporter.report(base_dir, ignore_errors=ignore_errors, merge_file=merge_file)
>
>  File "/home/travis/virtualenv/python2.7.12/lib/python2.7/site-packages/coveralls/report.py", line 15, in 
>report
>
>    with open(fr.filename) as fp:
>
>IOError: [Errno 2] No such file or directory: u'/var/machine-learning/__init__.py'

**Comment by ionelmc** [comment]
To know if the datafiles have been correctly remapped run `coverage report` before and after.

On the other hand you're running very old coverage (4.0.3) ....

**Comment by jeff1evesque** [comment]
I added [`coverage report`](https://travis-ci.org/jeff1evesque/machine-learning/builds/192458810#L4218-L4398) before, and after the [`coverage combine`](https://travis-ci.org/jeff1evesque/machine-learning/builds/192458810#L4308) command. It looks like the mappings did not get fixed, since it appears to error the same.  Additionally, my guess is that the old `coverage` (4.0.3) version was installed via [python-coveralls](https://github.com/z4r/python-coveralls) - so, I'm not sure if I should manually update `coveralls`?

**Comment by ionelmc** [comment]
https://github.com/z4r/python-coveralls is using a version pin, while https://pypi.python.org/pypi/coveralls doesn't.

I suspect there something missing in the coveragerc, not sure what but I can take a stab at figuring out the right config file for you if you provide me a sample `.coverage` file (one with the /var/machine-learning paths).

**Comment by jeff1evesque** [comment]
The following is my current [`.coverage`](https://travis-ci.org/jeff1evesque/machine-learning/builds/192458810#L4190) file:

>!coverage.py: This is a private format, don't read it directly!{"lines":{"/var/machine-learning/brain/session/__init__.py":[],"/var/machine-learning/brain/database/db_query.py":[128,129,131,132,133,134,135,172,146,147,148,149,151,152,153,154,33,34,35,38,41,44,47,50,53,63,64,71,72,73,74,75,77,79,80,81,82,105,106,107,110,111,113,114,125,126,127],"/var/machine-learning/brain/database/db_settings.py":[69,78,49,50,51,60],"/var/machine-learning/brain/converter/dataset/svm_xml_converter.py":[],"/var/machine-learning/brain/converter/dataset/svr_csv_converter.py":[],"/var/machine-learning/brain/database/save_observation.py":[33,34,35,36,37,52,55,58,62,63,65,68,69,72,73,75,76,77,78,82,83,86,89],"/var/machine-learning/brain/session/predict/sv.py":[42,43,44,47,48,49,50,51,52,53,57,60,61,62,63,66,67,68,69,71,72,73,74,75,76,77,79,83,84,85,86,87,89,90,91,92,93,95],"/var/machine-learning/puppet/environment/vagrant/modules/database/scripts/__init__.py":[],"/var/machine-learning/brain/session/data/save_entity.py":[],"/var/machine-learning/brain/session/data_new.py":[64,65,66,67,68,70,38,73,76,77,61],"/var/machine-learning/puppet/__init__.py":[],"/var/machine-learning/brain/database/save_account.py":[32,46,48,51,52,62,55,56,59,30,31],"/var/machine-learning/brain/session/data/__init__.py":[],"/var/machine-learning/brain/database/retrieve_session.py":[],"/var/machine-learning/brain/cache/__init__.py":[],"/var/machine-learning/puppet/environment/vagrant/modules/database/__init__.py":[],"/var/machine-learning/brain/session/data/save_dataset.py":[34,35,39,23,26,27,28,29,30],"/var/machine-learning/brain/converter/crypto.py":[98,99,100,101,102,81,57,55,78,79,80,56,82,83,53,54,23,24,25],"/var/machine-learning/log/logger.py":[133,134,137,138,139,140,143,144,145,55,56,59,60,61,62,63,66,69,70,71,87,89,91,93,94,101,104,107,110,111,112,119,120,123,126],"/var/machine-learning/brain/__init__.py":[],"/var/machine-learning/brain/converter/convert_dataset.py":[98,99,102,103,106,143,50,51,52,53,54,55,56,153,94,95],"/var/machine-learning/brain/validator/validate_dataset.py":[38,39,51,54,27,28,29],"/var/machine-learning/puppet/environment/docker/modules/database/scripts/__init__.py":[],"/var/machine-learning/brain/converter/dataset/svr_xml_converter.py":[],"/var/machine-learning/test/live_server/programmatic_interface/file_upload/pytest_svr_file_upload.py":[129,136,138,140,142,143,144,145,18,20,21,22,23,24,27,35,38,40,41,42,43,44,45,46,47,48,49,50,51,53,54,55,60,63,70,72,74,76,77,78,79,82,85,148,92,94,96,98,99,100,101,104,107,114,116,118,120,121,122,123,126],"/var/machine-learning/puppet/environment/docker/modules/database/__init__.py":[],"/var/machine-learning/puppet/environment/vagrant/modules/database/scripts/setup_tables.py":[],"/var/machine-learning/brain/database/retrieve_feature.py":[128,129,130,33,34,35,54,57,60,61,67,68,74,75,78,79,82,89,90,91,92,108,109,112,113,116,117,120,127],"/var/machine-learning/test/live_server/programmatic_interface/file_upload/pytest_svm_file_upload.py":[128,135,137,139,141,142,143,144,17,19,20,21,22,23,26,34,37,39,40,41,42,43,44,45,46,47,48,49,50,52,53,54,59,62,147,69,71,73,75,76,77,78,81,84,91,93,95,97,98,99,100,103,106,113,115,117,119,120,121,122,125],"/var/machine-learning/brain/validator/validate_file_extension.py":[129,130,131,132,133,135,144,151,154,34,35,49,50,52,53,57,101,102,103,104,105,108,109,111,112,113,115,116,117,120],"/var/machine-learning/test/live_server/conftest.py":[11,13,14,15,16,19,21,22,23,24,26,27,29],"/var/machine-learning/brain/session/predict/__init__.py":[],"/var/machine-learning/brain/load_data.py":[107,135,138,139,140,141,144,147,158,161,162,163,37,166,39,40,41,42,44,56,185,186,59,60,61,62,64,65,66,67,68,70,71,72,73,75,76,78,79,184,95,165,98,99,102,81,104,105,103,108,109,111,112,114,115,117,118,169,120],"/var/machine-learning/brain/session/data/save_feature_count.py":[32,36,37,40,30,31],"/var/machine-learning/brain/validator/validate_password.py":[96,66,67,68,135,136,137,138,43,44,45,108,81,82,83,21,22,23,109,95],"/var/machine-learning/brain/converter/calculate_md5.py":[],"/var/machine-learning/brain/converter/__init__.py":[],"/var/machine-learning/app.py":[],"/var/machine-learning/brain/cache/cache_model.py":[35,36,37,40,41,53,54,55,68,69],"/var/machine-learning/puppet/environment/__init__.py":[],"/var/machine-learning/brain/converter/serialize_model.py":[33,34,35,45,46,55,31],"/var/machine-learning/brain/converter/restructure_settings.py":[30,31,32,34,35,46,47,50,51,53,71,72,79,80,82,96,97,98,99,100,108,111,114],"/var/machine-learning/brain/validator/validate_settings.py":[33,34,35,50,53,54,55,56,61,62,63,64,69,70,71,72,77,78,79,81,82,83,85,90,93],"/var/machine-learning/brain/converter/dataset/svm_csv_converter.py":[],"/var/machine-learning/brain/database/retrieve_model_type.py":[64,61,47,48,53,54,57,58,28,29,30],"/var/machine-learning/puppet/environment/docker/modules/__init__.py":[],"/var/machine-learning/brain/cache/redis_settings.py":[40,50,29,30],"/var/machine-learning/brain/session/model/__init__.py":[],"/var/machine-learning/brain/session/base.py":[75,68,69,70,73,42,43,44,45,46,55,58,95],"/var/machine-learning/brain/schema/__init__.py":[],"/var/machine-learning/test/live_server/programmatic_interface/dataset_url/pytest_svm_dataset_url.py":[128,135,137,139,141,142,143,144,17,19,20,21,22,23,26,34,37,39,40,41,42,43,44,45,46,47,48,49,50,52,53,54,59,62,147,69,71,73,75,76,77,78,81,84,91,93,95,97,98,99,100,103,106,113,115,117,119,120,121,122,125],"/var/machine-learning/brain/validator/__init__.py":[],"/var/machine-learning/brain/session/model_generate.py":[64,65,66,67,68,72,42,43,44,45,46,82,58,59,62,63],"/var/machine-learning/brain/session/data/dataset_to_dict.py":[26,27,28,29,30,32,33,35,37,39,40,42,45,46,47,48,52,54,55,59,60,63,66,67,68,69,73,75,76,78,79,80,82,85,86,87,88,92,94,95,96,98,99,102,103,104,105,113,120,121,122,123],"/var/machine-learning/__init__.py":[],"/var/machine-learning/brain/database/retrieve_entity.py":[64,33,34,35,67,52,53,56,57,60,61],"/var/machine-learning/log/__init__.py":[],"/var/machine-learning/brain/session/base_data.py":[142,145,165,166,167,168,169,173,49,52,53,54,55,57,187,60,190,193,194,73,76,207,90,93,96,105,107,108,204],"/var/machine-learning/brain/schema/jsonschema_definition.py":[130,131,132,133,134,135,139,24,25,26,27,28,29,32,33,34,36,37,38,40,41,42,45,62,63,64,65,66,67,69,70,71,73,74,75,79,96,97,98,99,100,101,103,104,105,107,108,109,113],"/var/machine-learning/brain/converter/dataset/svr_json_converter.py":[130,131,132,133,137,141,142,145,146,147,148,32,33,34,35,38,39,40,41,44,47,48,50,51,53,57,58,59,60,64,65,68,69,70,72,73,75,79,80,81,82,86,87,91,93,95,98,99,101,102,104,108,109,110,111,115,116,119,120,121,123,124,126],"/var/machine-learning/brain/session/data_append.py":[64,67,68,39,55,56,57,58,59,61],"/var/machine-learning/brain/converter/dataset/__init__.py":[],"/var/machine-learning/test/live_server/authentication/pytest_user_logout.py":[32,35,36,37,10,12,15,27,42,30,31],"/var/machine-learning/brain/session/model_predict.py":[67,68,51,52,53,54,55],"/var/machine-learning/factory.py":[26,27,32,33,36,44,45,46,47,51,54,57,58,59,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,89,90,93,94,95,96,98,99,100,103,104,105,108],"/var/machine-learning/brain/database/save_feature.py":[34,35,36,37,38,39,53,54,57,58,60,63,64,67,70,86,87,88,91,92,95,97,98,99,100,102,105,106,109,112],"/var/machine-learning/test/live_server/authentication/pytest_user_login.py":[32,33,36,39,47,10,12,13,14,45,48,17,50,27,42,30,31],"/var/machine-learning/brain/session/data/validate_file_extension.py":[128,17,21,22,41,78,79,80,83,85,90,91,92,96,97,98,106,107,108,109,110,111,115,117,119,125],"/var/machine-learning/interface/views.py":[169,171,172,173,177,178,182,183,104,186,189,193,196,197,198,78,81,83,84,86,87,90,91,94,95,96,98,99,100,101,102,103,232,105,234,237,240,113],"/var/machine-learning/brain/database/save_entity.py":[65,66,75,68,69,39,40,41,42,43,77,80,81,74,73,84,87,59,61,62],"/var/machine-learning/test/live_server/programmatic_interface/dataset_url/pytest_svr_dataset_url.py":[129,136,138,140,142,143,144,145,18,20,21,22,23,24,27,35,38,40,41,42,43,44,45,46,47,48,49,50,51,53,54,55,60,63,70,72,74,76,77,78,79,82,85,148,92,94,96,98,99,100,101,104,107,114,116,118,120,121,122,123,126],"/var/machine-learning/brain/cache/cache_hset.py":[33,34,37,38,49,50,62,63],"/var/machine-learning/brain/database/retrieve_account.py":[130,133,31,32,33,43,44,47,48,51,52,55,58,68,69,72,73,76,77,80,83,93,94,97,98,101,102,105,108,118,119,122,123,126,127],"/var/machine-learning/puppet/environment/docker/modules/database/scripts/setup_tables.py":[],"/var/machine-learning/puppet/environment/docker/__init__.py":[],"/var/machine-learning/brain/database/__init__.py":[],"/var/machine-learning/test/live_server/authentication/pytest_account_registration.py":[34,37,40,44,10,43,12,13,14,15,18,25,47,28,29,30,31],"/var/machine-learning/puppet/environment/vagrant/modules/__init__.py":[],"/var/machine-learning/interface/__init__.py":[],"/var/machine-learning/brain/converter/dataset/svm_json_converter.py":[128,132,133,134,135,139,140,143,144,147,148,149,150,32,33,34,35,38,39,41,43,46,47,49,50,52,56,57,58,59,63,67,68,69,71,72,74,78,79,80,81,85,86,89,93,94,97,100,101,103,104,106,110,111,112,113,117,118,121,122,123,125,126],"/var/machine-learning/brain/cache/redis_query.py":[64,65,66,323,92,332,55,89,58,91,60,90,94],"/var/machine-learning/brain/session/model/sv.py":[128,129,130,131,135,30,31,32,33,34,37,42,45,50,53,54,55,56,57,58,61,63,64,66,67,68,69,72,73,75,76,77,78,81,82,85,87,88,89,92,95,98,101,103,106,109,110,111,112,113,117,118,121,122,123,125],"/var/machine-learning/puppet/environment/vagrant/__init__.py":[],"/var/machine-learning/brain/cache/redis_session.py":[],"/var/machine-learning/brain/session/data/save_observation_label.py":[18,21,22,23,24,25,26,27,28,30,34,35,40,41,42,43,44,45,47,51,52,56]}}

Also, in a previous commit, I had removed my the `.coveragerc` file, since it wasn't explicitly referenced anywhere, making me question if it was needed (concluded it wasn't).  If we add back `.coveragerc`, do we need to make a reference of it somewhere?

**Comment by ionelmc** [comment]
No, coverage will load it by default. It is necessary for the combine to adjust paths.

**Comment by jeff1evesque** [comment]
I added back in [`.coveragerc`](https://github.com/jeff1evesque/machine-learning/blob/d995dab7a0aed0e8b6a5371c604c6abaad48aaf1/.coveragerc), pushed the commit to github, which produced the same [traceback](https://travis-ci.org/jeff1evesque/machine-learning/builds/192479962#L4211-L4403) from the corresponding travis build.

**Comment by ionelmc** [comment]
Ah yes, `coverage combine` only does anything if there are files like `.coverage.suffixblablabla`. Quick workaround is to `mv .coverage .coverage.123` and then run `coverage combine --append`. Then your report will have the right paths.

There should be a better way, maybe @nedbat knows. Or maybe there should be a coverage command that only does source path fixups ...

**Comment by jeff1evesque** [comment]
Hi @ionelmc, wow it [worked](https://travis-ci.org/jeff1evesque/machine-learning/builds/192506748#L4208-L4309)!

**Comment by ionelmc** [comment]
I think we ca close this then. If you want nicer handling complain in coverage's bugtracker.
