### ISSUE TITLE
code that is executed in the doctests is not covered.

### ISSUE THREAD

**Issue by thisch** [pytest-dev/pytest-cov#162]
If parts of your code are only tested in doctests but not in conventional unit tests then the code that is called by the doctests is marked as not covered. Note that I'm not speaking of the code in the doctest itself.

It would be nice if the code called by the doctests could be considered for the final coverage.

**Comment by ionelmc** [comment]
@thisch do you have a reproducer?

**Comment by thisch** [comment]
the "testspaths" option in setup the "tool:pytest" section of setup.cfg was unfortunately missing the directory containing the doctests. Therefore the doctests were not executed.

I'm sorry for wasting your time, but I'm grateful that you urged me to post a reproducer ;)
