### ISSUE TITLE
Windows: coverage through multiprocessing not catched correctly

### ISSUE THREAD

**Issue by Makman2** [pytest-dev/pytest-cov#165]
Hi ;)

Recently I'm trying to get the test coverage to 100% on a windows machine, but it doesn't want to. My code under test uses an event-loop driven by a `concurrent.futures.ProcessPoolExecutor`. Coverage is 100% on a Linux machine, but not on Windows.

PR:
https://github.com/coala/coala/pull/4475
Build on AppVeyor:
https://ci.appveyor.com/project/coala/coala/build/1.0.7774
Same build but on Linux (Travis):
https://travis-ci.org/coala/coala/builds/254572218?utm_source=github_status&utm_medium=notification
Relevant Python module/components under test:
https://github.com/coala/coala/tree/8f4113a2f471acf4c0121199c6ebb9b29dfa84ff/coalib/core, specificially
- https://github.com/coala/coala/blob/8f4113a2f471acf4c0121199c6ebb9b29dfa84ff/coalib/core/FileBear.py
- https://github.com/coala/coala/blob/8f4113a2f471acf4c0121199c6ebb9b29dfa84ff/coalib/core/ProjectBear.py

The missing lines are the ones inside `def execute_task`.

`setup.cfg` (and yes, coverage is enabled ;D):
https://github.com/coala/coala/blob/8f4113a2f471acf4c0121199c6ebb9b29dfa84ff/setup.cfg#L32

Exchanging the `ProcessPoolExecutor` with a `ThreadPoolExecutor` does the trick and produces full coverage. However it would be nice to have everything being tested with a `ProcessPoolExecutor` (especially due to possible pickling issues on Windows for subprocesses).

Not proven assumption:
I have the feeling that other parts of the code only run through a subprocess is measured properly, only those two modules under test don't work.

**Comment by ionelmc** [comment]
I suspect this is related to #139. A problem with Windows it's impossible to get 100% clean process termination (no sigterm, you either tell it to exit via ipc and wait, or you kill it).

**Comment by ionelmc** [comment]
How do you shutdown the executor in coala?

**Comment by Makman2** [comment]
Thanks for the quick response ;)

I'm waiting until all remaining tasks are processed. I wait with `event_loop.run_forever()` until `event_loop.stop()` is called. After that `event_loop.close()` is called for cleanup.
(See https://github.com/coala/coala/blob/8f4113a2f471acf4c0121199c6ebb9b29dfa84ff/coalib/core/Core.py#L360)

**Comment by Makman2** [comment]
Is this considered a "good" shutdown?

**Comment by ionelmc** [comment]
I doubt your ioloop magically figures out that `executor.shutdown()` needs to be run at some point ... try fixing that first.

**Comment by Makman2** [comment]
Damn yeah, that makes totally sense... I've actually forgotten that I always pass the executor explicitly to `event_loop.run_in_executor`, so how shall it know about my executor's lifetime...

I'm currently trying that out on the CI, I hope that does the trick :D

**Comment by Makman2** [comment]
No effect, tried to shutdown the executor manually at different places (inside the done-callback of my futures before and after `event_loop.stop()`, immediately before `event_loop.close()`), and also tried to register the executor as default (with `event_loop.set_default_executor`) with the hope that the event-loop takes the shutdown over completely.

**Comment by Makman2** [comment]
Any other ideas? :/

(I did workaround the problem now by executing my tests also with a `ThreadPoolExecutor`, where coverage data is correctly merged)

**Comment by ionelmc** [comment]
@Makman2 seems the branch is gone? can you republish it somewhere so I can try it?

**Comment by Makman2** [comment]
Oh I accidentally removed it... my bad sorry :/
Recreated problem on https://github.com/coala/coala/pull/4589

**Comment by Makman2** [comment]
Corresponding Windows build:
https://ci.appveyor.com/project/coala/coala/build/1.0.9309/job/bvh96djsd64dfmmw

**Comment by ionelmc** [comment]
Well I've tried to run it locally but it has failed tests and the whole suite timeout (no coverage report).  Please provide a more minimal reproducer.

**Comment by Makman2** [comment]
PS: To run the tests you need to install the requirements:
```
pip3 install -r requirements.txt -r test-requirements.txt
```

**Comment by ionelmc** [comment]
What I had in mind is something that don't involve your codebase or your test suite. At least nail it down for me to a single test. "core" selects a ton of borken tests.

**Comment by Makman2** [comment]
This takes a while, I hope I can reproduce it^^

**Comment by ionelmc** [comment]
Are you saying the problem doesn't reproduce if you make a small test with just the executor?

**Comment by ionelmc** [comment]
Anyway, so I've managed to find a problem with a test like this:
```python
import os
from concurrent.futures import ProcessPoolExecutor


def my_func(_):
    print('FUNC:', [i for i in os.environ if i.startswith('COV')])
    a = 1
    b = 2
    return a + b


def test_mp():
    print('PARENT:', [i for i in os.environ if i.startswith('COV')])

    with ProcessPoolExecutor() as executor:
        assert list(executor.map(my_func, [1])) == [3]
```

It turns out if you use bare `--cov` the mp subprocess will not have the `COV_CORE_SOURCE` set cause of some weird windows problem: if env var is empty then it's gonna be unset in the child. A fix will follow shortly.

PS. Don't make bug reports like this no more. I'll try to look over other peoples projects but this is taking it too far.

**Comment by ionelmc** [comment]
Try the latest master.

**Comment by Makman2** [comment]
Yes the commit was the fix. Thanks :+1:
