### ISSUE TITLE
Document/implement how to specify multiple sources

### ISSUE THREAD

**Issue by altendky** [pytest-dev/pytest-cov#169]
Presently `README.rst` states:

```
Note that this plugin controls some options and setting the option in the config file will have no effect. These include specifying source to be measured (source option) and all data file handling (data_file and parallel options).
```

I also find no reference to passing multiple source specifications to `--cov`.  This leaves no apparent ability to specify multiple sources such as your package and also the tests themselves.

**Comment by altendky** [comment]
This seems related to the title of #130 but not so obviously to the contents.

**Comment by smcoll** [comment]
Try `pytest --cov=foo --cov=bar`
