### ISSUE TITLE
Document how to use append

### ISSUE THREAD

**Issue by oppianmatt** [pytest-dev/pytest-cov#170]
There is a section in the docs:

> Coverage Data File
> 
> The data file is erased at the beginning of testing to ensure clean data for each test run. If you need to combine the coverage of several test runs you can use the --cov-append option to append this coverage data to coverage data from previous test runs.
> 
> The data file is left at the end of testing so that it is possible to use normal coverage tools to examine it.

But it's very light on details. What data file is left over?

My use case is as follows. I split my tests into groups for running in parallel using cloud instances using https://github.com/mark-adams/pytest-test-groups

This produces a separate report for each group. I would like to have a step that combined all the reports into one at the end. Is this possible?

Reading about cov-append seems to indicate so. I just need to know what data files it needs to be persisted.

**Comment by yangineer** [comment]
Would a link to https://coverage.readthedocs.io/en/coverage-4.4.2/cmd.html#data-file be suffice?

**Comment by ionelmc** [comment]
Yeah a link to that would help but I think we need a section on dealing with tox-like scenarios.
