### ISSUE TITLE
Recursion error while installing

### ISSUE THREAD

**Issue by daegontaven** [pytest-dev/pytest-cov#172]
I'm trying to test my application using pytest. I only have pytest-cov as dependency for the tests even though I'm not actually using it. However, for some reason it's not installing on travis for python 3.5. It  displays a recursion error while installing. This issue does not exist on python 3.6.

The full log can be viewed [here](https://travis-ci.org/AlphaHooks/AlphaHooks/jobs/281456582#L569).

**Comment by RonnyPfannschmidt** [comment]
at first glance this looks like a setuptools issue as none of the code of pytest-cov seems involved

**Comment by RonnyPfannschmidt** [comment]
does it still fail if you install the test dependencies using pip beforehand?

**Comment by daegontaven** [comment]
@RonnyPfannschmidt Tbh I hadn't even considered setuptools might be the culprit. I'll update to see if it breaks even after installing it separately.

https://github.com/pypa/setuptools/issues/946

**Comment by daegontaven** [comment]
@RonnyPfannschmidt Thanks for pointing it out to me. Looks like the builds are passing now. Thank you !
