### ISSUE TITLE
Coverage of remote services

### ISSUE THREAD

**Issue by TheFriendlyCoder** [pytest-dev/pytest-cov#173]
This is more of a question than a defect, but I'm just wondering if there is any way to use pytest-cov, maybe with the `--dist` flag, to gather metrics from code stored and executed on a remote server?

Here's the use case I have: I have a Python library I'm writing which interacts with a third party service. To test my library I have a pytest framework that launches a Docker container with the third party service installed on it, then I install my library inside the container, then I execute my test code. The testing logic then interacts with the third party service to flex the behavior of my library.

The problem here is that the Python runtime running my library isn't on my host / local machine, it's inside the docker container... and my scripts are invoked directly by the test API, but rather indirectly via the third party service running in the container.

So my question is: is there any way for me to set up the Python environment inside the Docker container to somehow run pytest and track the coverage metrics of any and all calls made to my library, and then accumulate those metrics and report them by the pytest runner running on the host?

**Comment by TheFriendlyCoder** [comment]
Based on my limited understanding of the `--dist` flag what I was thinking might be a workable approach is if I added a hook between the third party service and my library to call pytest inside the Docker container such that when calls are made to my library metrics about the call can be gathered and stored on disk. If I could then share those on-disk metrics generated within the container with my host via a bind-mounted shared folder (ie: a folder shared between the Docker container and my pytest workspace) then perhaps the metrics from those Docker generated metrics could be combined with the metrics gathered by the pytest runner on my host to produce a single master report.

From what I can tell, pytest-cov does have a feature that can "append" metrics from one pytest run to another. I'm assuming the behavior I'm looking for here would be largely the same ... only instead of "appending" metrics from many independent test runs they'd be "aggregated" across several different source files / report files.

If this sounds totally out there and impossible, feel free to let me know. :)

**Comment by ionelmc** [comment]
So is there a problem with the append mode or what's stopping you from using it?

**Comment by TheFriendlyCoder** [comment]
So my first problem I guess is to figure out whether or not I can use pytest-cov to generate coverage metrics for a Python library not running under the pytest runner. If you can suggest a command line I might be able to use to execute a python script in such a way that a pytest-cov compatible report file gets generated that would be awesome.

Then my second problem would be to figure out how one can execute py-test such that coverage metrics are gathered primarily via metrics gathered from the local runtime environment (ie: the instrumented code of my locally stored library) but then aggregated with metrics stored in one or more independent / external report files stored elsewhere on disk. Again, if you can suggest a command line to accomplish this behavior that would be great.

NOTE: All of this hinges on whether or not pytest and pytest-cov actually support what I'm trying to do at all. So if you have any other alternative suggestions feel free to let me know.

**Comment by ionelmc** [comment]
My suggestion is to use pytest-cov's append mode and then on the remote side (docker or whatever it is) you can either:
A) - Run your code with coverage (see https://coverage.readthedocs.io/ for how to activate)
B) - Run your code with pytest-cov's engine (if you need the subprocess handling and such). For this you only need to set 3 env vars:
  
  - COV_CORE_SOURCE=src or whatever
  - COV_CORE_CONFIG=path/to/.coveragerc
  - COV_CORE_DATAFILE=path/to/.coverage.somesuffix

Note that the suffix is necessary if you don't have unique hostnames.

Also, your `.coveragerc` should at least have:
```
[run]
parallel = true 
```

If you get stuck or need more clarifications let me know.

**Comment by TheFriendlyCoder** [comment]
I do have one preliminary question: when using pytest-cov's "append" feature, do I need to point both my pytest-runner and the "coverage" tool to the same report file for this to work? Will this cause a problem if both the pytest runner and the coverage tool try to access the report file at the same time?

**Comment by ionelmc** [comment]
Not sure what you mean by report file. There's the html report but that is multiple files.

Also, what's pyteset-runner?

Coverage will normally save the coverage data in a `.coverage` file. That's why you need the parallel mode, so the datafile becomes `.coverage.<hostname>.<pid>.<somenumbe>`. Then you don't have name collisions.

Note that pytest-cov just uses Coverage underneath.

**Comment by TheFriendlyCoder** [comment]
Thanks for clarifying the use of the .coverage file. That was what I was trying to refer to previously.

However wrt reporting, I would assume that pytest-cov typically uses the data in the .coverage file generated for the current test run to generate reports (ie: `--cov-report term` say). Is there any extra parameters that need to be provided to have that report include the aggregated results from all of the .coverage files?

**Comment by ionelmc** [comment]
Yes, pytest-cov will combine all the datafiles before doing the report. But you can run „coverage combine/report” regardless (eg: if you copy datafiles after running tests).

**Comment by TheFriendlyCoder** [comment]
Ok - so I think I have this mostly working. I've added a call to `coverage run` inside my docker container, and I've confirmed the tool correctly generates a .coverage file for the source files running inside the container. Then I've shared this file with my host PC and I've confirmed that `coverage combine` successfully merges the .coverage file generated from within the container with the .coverage file generated by pytest-cov on my host....

However, `coverage report` throws some errors and produces a partial report. It seems that when `coverage combine` runs it uses absolute paths for the .py files that were instrumented during the metric gathering process... and since the paths to my library packages are different inside the Docker container than they are on my host, it gets confused. It seems combine isn't smart enough to map metrics from, say `/opt/lib/python3.4/site-packages/mylib/__init__.py` with the metrics for `$PWD/mylib/__init__.py`.

Do you have any recommendataions on how to work around this problem? One thing I had in mind was to hack the .coverage file generated inside my container to rewrite the paths from the container to their respective locations on my host before running `coverage combine`, but I'm hoping there will be a more robust and less hack-ish way of doing this.

**Comment by ionelmc** [comment]
But it is smart enough :) Just need to configure it properly: http://coverage.readthedocs.io/en/latest/config.html#paths

**Comment by TheFriendlyCoder** [comment]
Sweet! I knew there must be an option for that.

I've already incorporated that into my test environment and PRESTO - it's working as I had hoped! Thank you so much for the help on this!
