### ISSUE TITLE
pytest-cov coverage.xml does not reflect multiple hits of a line

### ISSUE THREAD

**Issue by nikhilh-20** [pytest-dev/pytest-cov#179]
All information with respect to pytest version 3.0.7 on a RHEL 2.6.32-504.3.3.el6.x86_64

I'm working on getting the coverage data of test files.
Here's my pytest setup:

basic.py
```
class Basic():
    def __init__(self):
        print ('Basic initialized')
    def add_num(self, num1, num2):
        counter = 0
        while (counter < 5):
            print (counter)
            counter = counter + 1
        return (num1 + num2)

```

test_basic.py
```
class TestCalculator():
    def test_calculator(self):
        from basic import Basic
        basic_obj = Basic()
        sum_nums = basic_obj.add_num(1,2)
```

.coveragerc
```
[run]
branch = 1

[report]
fail_under = 95
show_missing = True
precision = 2

[xml]
output = coverage.xml
```

I'm running pytest as:
`py.test --cov-report xml --cov=test/lib test/lib/test_basic.py`

This is a snippet of the data that coverage.xml contains:
```
<classes>
<class branch-rate="1" complexity="0" filename="test/lib/basic.py" line-rate="1" name="test/lib/basic">
    <methods/>
    <lines>
        ...
        ...
        <line hits="1" number="5"/>
        <line branch="true" condition-coverage="100% (2/2)" hits="1" number="6"/>
        <line hits="1" number="7"/>
        <line hits="1" number="8"/>
        ...
        ...
```

In basic.py, line 6,7,8 are executed multiple times (6, 5, 5 times respectively). 
coverage.xml `line hits` does not reflect this number. Is there any development on this? Or is there any available hack that I can use?

Thanks!

**Comment by ionelmc** [comment]
AFAIK Coverage doesn't actually count number of times code is executed (just that it is). Pytest-cov just uses coverage.

Coverage's bug tracker is best place for this https://bitbucket.org/ned/coveragepy/issues

**Comment by nikhilh-20** [comment]
Thanks for the info @ionelmc 
I've created an issue at bitbucket:
[https://bitbucket.org/ned/coveragepy/issues/614/pytest-cov-coveragexml-does-not-reflect]
