### ISSUE TITLE
Omiting folders for coverage from setup.cfg

### ISSUE THREAD

**Issue by sebastian-code** [pytest-dev/pytest-cov#180]
I'm running on my project PyTest and Coverage, and I'm trying to implement this plugin, the issue I'm having is than I haven't been able to make it run omitting some folders, and I haven't been able to make it run as automated as I want.

Perhaps what I need is more help than reporting an issue, but up to now I haven't been able to find a way it picks the `omit=` line, perhaps is related to additional configurations.

My libraries:
```
Python 3.5.2
coverage==4.0.3
pytest==3.2.3
pytest-cov==2.5.1
pytest-django==2.9.1
pytest-flake8==0.9.1
pytest-sugar==0.7.1
django-coverage-plugin==1.3
```
My `setup.cfg` file (Partially, the last part is for PyLint and is really long):

```
[tool:pytest]
DJANGO_SETTINGS_MODULE=config.settings.local
python_files=tests.py test_*.py *_tests.py
addopts=--cov=accountant --cov-config setup.cfg

[coverage:run]
source=accountant/*
omit=*/migrations/*,*/tests/*
plugins=django_coverage_plugin

[flake8]
max-line-length=80
exclude=.tox,.git,*/migrations/*,*/static/CACHE/*,docs,node_modules,build,dist,*.egg-info
statistics=True
```

**Comment by ionelmc** [comment]
Are you using xdist or subprocesses? Or changing CWD in tests?

**Comment by sebastian-code** [comment]
Hi @ionelmc 

No, I'm not using xdist nor subprocesses, neither changing CWD in tests. The project is a Django Project with unittest inside every app, but anything else beside that.

**Comment by sebastian-code** [comment]
Hi @ionelmc I have been testing this but up to now haven't been able to find a fix using the same `setup.cfg` file, I turned to keep the `addopts` parameter like this:
```
addopts=--cov=bootcamp --cov-config .coveragerc
```
Using the previous `.coveragerc` file for that, but that is what I wanted to avoid. Is there something I'm doing the wrong way?

**Comment by ionelmc** [comment]
Ah whoops I forgot about this. I'll try to reproduce. This reproduces with latest coverage (4.4.2) as well right?

**Comment by sebastian-code** [comment]
I haven't tested that before, apparently is a bug with the previous version because is working now.

**Comment by neozenith** [comment]
Is this still an issue or could this be closed @sebastian-code ?

**Comment by blueyed** [comment]
According to the previous comment I am going ahead and close this already.
