### ISSUE TITLE
Miss module scope coverages when `python setup.py test` sometimes

### ISSUE THREAD

**Issue by yanqd0** [pytest-dev/pytest-cov#187]
When working with `pytest`, it is OK. But if working with `python setup.py test` and without pytest-cov installed explicitly, the module scope coverages will be missing.

This bug can be reproducted in any platform. For example:

```sh
git clone https://github.com/yanqd0/csft.git
cd csft
pip install . -r requirements.txt
```

The test result is something like this:

```console
$ python setup.py test
Name               Stmts   Miss  Cover
--------------------------------------
csft/__init__.py      17      7    59%
csft/__main__.py      43     14    67%
csft/_csft.py         52      1    98%
--------------------------------------
TOTAL                112     22    80%
```

This is OK.

But if I uninstall `pytest-cov`, and run `python setup.py test` again, the result will change.

```console
$ pip uninstall pytest-cov -y
Uninstalling pytest-cov-2.5.1:
  Successfully uninstalled pytest-cov-2.5.1
$ python setup.py test
Name               Stmts   Miss  Cover
--------------------------------------
csft/__init__.py      17     17     0%
csft/__main__.py      43     15    65%
csft/_csft.py         52     18    65%
--------------------------------------
TOTAL                112     50    55%
```

The missing parts are all in module scope, like imports and defs.
There is a related demo page in [codecov](https://codecov.io/gh/yanqd0/csft/tree/9ff975d0448b1befb779984ebf0cc26a54c04640/csft).

**Comment by ionelmc** [comment]
Well there's your problem: https://github.com/yanqd0/csft/blob/master/setup.py#L9

See https://packaging.python.org/guides/single-sourcing-package-version/

**Comment by yanqd0** [comment]
Yes, that's the cause. The import in setup.py maybe confuses the coverage program.
Thank you!
