### ISSUE TITLE
Excluding files/folder from code coverage

### ISSUE THREAD

**Issue by javixeneize** [pytest-dev/pytest-cov#193]
Hi

Im running pytest to check the code coverage. However its analysing some files that i dont want to analyse, as i have stubbed version of it in a different folder

Is there any argument to exclude files or folders from code coverage?

The command im running is python -m pytest --cov=src

Thanks

**Comment by karthik-ir** [comment]
Is there a command line alternative to this ?

**Comment by blueyed** [comment]
@karthik-ir 
pytest-cov only provides `--cov` (mapped to `source`).
You should really use a config file when adding coverage to a project in the long run.

**Comment by mcallaghan-bsm** [comment]
Specifically, see https://coverage.readthedocs.io/en/latest/source.html#source.
I think you are looking for `omit`

**Comment by anilbey** [comment]
https://pytest-cov.readthedocs.io/en/latest/config.html?highlight=exclude
