### ISSUE TITLE
Does pytest-cov co-works with pytest if a test is marked with @pytest.mark.skipif?

### ISSUE THREAD

**Issue by eundoosong** [pytest-dev/pytest-cov#194]
If a test is disabled due to skipif mark provided by pytest, I think it shouldn't check the coverage as well.
But I can't find any option in pytest-cov that makes it available.
I found, only options provided is adding "exclude list" into .coveragerc or "# pragma: no cover"  for code in each file.
```python
@pytest.mark.skipif('moduleA' not in sys.modules,
                    reason="requires moduleA library")
def test_A(self):
        # Some test code with assert
```
If it doesn't co-work with pytest in such case, does pytest-cov support a conditional api for excluding  test  as "pytest.mark.skipif" does?
Thanks.

**Comment by nicoddemus** [comment]
Hi @eundoosong,

> I think it shouldn't check the coverage as well.

Coverage of what, the test code or the code being tested? 

If you mean the test code, then I don't think it makes sense to run coverage over the test code at all, at least not in general.

If you mean the code being tested, then currently `pytest-cov` (and `coverage`) doesn't track exactly which code is being exercised by each test, and is not designed for that.

**Comment by eundoosong** [comment]
@nicoddemus  
I'm talking about "the code being tested". 
Thanks for clarifying.  
Then, is there any way to skip "a file being tested" conditionally in pytest-cov?
For example, **a file being tested is skipped IF prometheus_client is not installed**
I already know .coveragerc, but it just provides fixed exclude list

**Comment by RonnyPfannschmidt** [comment]
coverage literally has no idea how you check what tests to run and what not
currently coverage is unaware of conditional skipping as far as  i know,
and until it gets the utilities for that i dont see how to add it

**Comment by eundoosong** [comment]
Thanks for clarifying.
