### ISSUE TITLE
identifying most relevant failure / integrations & public API

### ISSUE THREAD

**Issue by dchudz** [pytest-dev/pytest-cov#201]
I'm interested in creating functionality for identifying the most relevant among a bunch of failures (by finding the failure whose covered lines are a subset of all other failures' covered lines).

I've done this in a small prototype package (https://github.com/dchudz/besttest) by subclassing pytest-cov's `CovPlugin` and `Central` controller.

That's kinda gross, so I'm wondering:

- is this a feature you'd be interested in for pytest-cov itself (off by default)?
- if not, do you have any suggestions for integrating with pytest-cov?

**Comment by ionelmc** [comment]
@dchudz That controller API is there for a long time (older than https://github.com/pytest-dev/pytest-cov/commit/7c6448ddf699c20323068ee7c2a17aa60fd3a3ae I suppose). From that time it only got moved to a different file and got fixes. Pretty sure you can use it.

I'm not really hot about adding huge features in pytest-cov - it's already packed with complicated stuff for subprocess measurements. I'm open for helping you getting integration tests going on so we don't break besttest if we ever change those classes tho. Lets talk about that.

**Comment by dchudz** [comment]
Thanks! You're right, it seems pretty stable. :) Probably no problem using it in my thing if I work on it more.
