### ISSUE TITLE
Option to fold multiple tox environment installs into one report?

### ISSUE THREAD

**Issue by madig** [pytest-dev/pytest-cov#203]
I want to switch from using coverage directly to pytest-cov because I can't get subprocess coverage to work. I currently have
```
[...]
[paths]
source =
    Lib/mypkg
    .tox/*/Lib/python*/site-packages/mypkg
    .tox/*/Lib/site-packages/mypkg
[...]
```
in my `.coveragerc` file -- the last line is necessary on Windows because there, stuff gets installed to `.tox/py36/Lib/site-packages` instead of `.tox/py36/Lib/python3.6/site-packages` as on Linux. The documentation says the option in the rc file is ignored, so how do I add the path I need?

**Comment by ionelmc** [comment]
How about this?
```
[paths]
source =
   src
   */site-packages
```
Also, don't forget `--cov-append`.

**Comment by madig** [comment]
That did the trick! Thanks! 😃
