### ISSUE TITLE
Don't measure coverage from certain lines

### ISSUE THREAD

**Issue by pckroon** [pytest-dev/pytest-cov#207]
Hi all,

I have a project that, on import, reads some datafiles. pytest-cov (and coverage) measure this code as being covered, even though it isn't actually tested (so long as it doesn't error). So my question, is there anyway to prevent coverage from measuring (not just reporting) those import snippets? Is it possible to record a "background" that should be substracted from the actual test results?
I know this is probably more of an issue for coverage than pytest-cov, but maybe a solution is known here as well.

Peter

**Comment by blueyed** [comment]
`# pragma: not covered` ?

**Comment by pckroon** [comment]
Hi, thanks for the fast reply.
Unfortunately it doesn't seem to work, for the offending file it gives the same coverage whether I do
`import project.data  # pragma: no cover` or `import project.data`. I do run `coverage erase` in between.
Any more ideas before I take this upstream?

**Comment by blueyed** [comment]
Does it mark the `import project.data` as not covered then?
But you want to mark/ignore the whole file?
What about using a `.coveragerc` (or `[coverage]` section in setup.cfg) to `omit` with `[run]` and `[report]`?

But yeah, likely better to take this upstream.

**Comment by pckroon** [comment]
I think a minimal example might help:
```
project
|-setup.py
|-project
||-data.py
||-func.py
||-__init__.py
|-tests
||-test_x.py
||-test_data.py
```

`project/__init__.py`:
```
from .func import f
```

`project/data.py`:
```python
def parse_datafile():
    return 8

a = parse_datafile()
```

`project/func.py`:
```python
def f(x): return x**2
```

`tests/test_x.py`
```python
from project.data import a  # pragma: no cover                                  
from project import f                                                           
                                                                                
def test_f():                                                                   
    assert f(a) == a**2                                                         
```

`tests/test_data.py`:
```python
from project.data import parse_datafile  # pragma: no cover

def test_parse():
    assert parse_datafile() == 8
```

```bash
> coverage erase && pytest --cov=project tests/test_x.py
============================= test session starts ==============================
platform linux -- Python 3.5.2, pytest-3.6.0, py-1.5.3, pluggy-0.6.0
rootdir: /home/peterkroon/python/coverage_meuk, inifile:
plugins: cov-2.5.1
collected 1 item                                                               

tests/test_x.py .                                                        [100%]

----------- coverage: platform linux, python 3.5.2-final-0 -----------
Name                  Stmts   Miss  Cover
-----------------------------------------
project/__init__.py       1      0   100%
project/data.py           3      0   100%
project/func.py           2      0   100%
-----------------------------------------
TOTAL                     6      0   100%
```

I expect `project/data.py` to be 0% covered, unless I also run `test_data.py`. I can't make that work with a .coveragerc either. Any further advice is highly welcome :)

**Comment by pckroon** [comment]
I also posted this issue upstream: https://bitbucket.org/ned/coveragepy/issues/668/

**Comment by nedbat** [comment]
Seems like this issue can be closed here, since we have https://github.com/nedbat/coveragepy/issues/668.
