### ISSUE TITLE
warning "Module x was never imported" when running with xdist

### ISSUE THREAD

**Issue by anthrotype** [pytest-dev/pytest-cov#212]
If I install pytest-xdist plugin, and run `pytest --cov` with some `-n` number of parallel processes (even with `-n 1`), I get this warnings at the end:

```
Coverage.py warning: Module psautohint was never imported. (module-not-imported)
Coverage.py warning: No data was collected. (no-data-collected)
```

However, the data is collected, the `.coverage.*` data file is created, and a report is printed correctly despite the warnings.

If I run without passing the -n xdist option, so not in parallel, I don't get any such warnings.
Similarly I don't get those warning if I run `coverage run -m pytest` instead of `pytest --cov`.

I have a .coveragerc file in the root of the repository which contains this:

```
source = psautohint

[paths]
source =
    src/psautohint
    .tox/*/lib/python*/site-packages/psautohint
    .tox/*/lib/site-packages/psautohint
    .tox/pypy*/site-packages/psautohint
```

**Comment by ionelmc** [comment]
How can I reproduce this? Enough to checkout https://github.com/adobe-type-tools/psautohint and run tox-something?

**Comment by anthrotype** [comment]
thanks for looking into this. Yes, you can just clone and run `tox`, you should get a warning like this
https://travis-ci.org/adobe-type-tools/psautohint/jobs/414896624#L498

**Comment by ionelmc** [comment]
Check the new examples from #267 - they should clarify how to correctly use pytest-cov in your project.

**Comment by anthrotype** [comment]
Thank you!

**Comment by manoadamro** [comment]
having the same problem, was working fine, now, having changed exactly nothing (i hit the up arrow and then enter) 
it's importing everything from site packages (on a different hard drive) but for all the source files it says "module was never imported", yet hundreds of tests that use that module ran and passed...

Is there any known reasons as to why I can only use coverage on windows a couple of times before it completely breaks? I have never had this issue on mac
