### ISSUE TITLE
Pluggy incompatibility with pytest==3.7.0 when using pipenv

### ISSUE THREAD

**Issue by benhowes** [pytest-dev/pytest-cov#216]
When updating in pipenv today:

```
$> pipenv install
Pipfile.lock (bd627c) out of date, updating to (5f00e3)...
Locking [dev-packages] dependencies...

Warning: Your dependencies could not be resolved. You likely have a mismatch in your sub-dependencies.
  You can use $ pipenv install --skip-lock to bypass this mechanism, then run $ pipenv graph to inspect the situation.
  Hint: try $ pipenv lock --pre if it is a pre-release dependency.
Could not find a version that matches pluggy<0.7,>=0.5,>=0.7
Tried: 0.3.0, 0.3.0, 0.3.1, 0.3.1, 0.4.0, 0.4.0, 0.5.0, 0.5.1, 0.5.1, 0.5.2, 0.5.2, 0.6.0, 0.6.0, 0.6.0, 0.7.1, 0.7.1
There are incompatible versions in the resolved dependencies.
```
I cannot see a way in which pytest-cov directly depends on pluggy though?

**Comment by nicoddemus** [comment]
I'm not sure either, but `pytest 3.7.0` has changed `pluggy` pinning from `>=0.5,<0.7` to `>=0.7` in case this helps finding the issue. Perhaps is some other dependency pinning `pluggy`?

**Comment by gaffney** [comment]
Same issue today; `pytest` itself installs fine but the tools do not:
- `pytest-cov` - causes this issue
- `pytest-mock` - causes this issue
- `pytest-xdist` - causes this issue
- `pytest-helpers-namespace` - causes this issue

I do not understand this issue because `pipenv install --dev --skip-lock && pipenv graph` does _not_ show conflicts. Maybe this is a `pipenv` bug... ?

**Comment by gzagatti** [comment]
I am having this same issue and I believe it is related with the issue in [here](https://github.com/pypa/pipenv/issues/2596). It has to do with `pipenv` lack of backtracking.

**Comment by benhowes** [comment]
@gzagatti appears to be correct, https://github.com/pypa/pipenv/issues/2596#issuecomment-409468238 solved this problem for me.

**Comment by benhowes** [comment]
I'll close this because that confirms it's a pipenv problem, not pytest/pytest-cov
