### ISSUE TITLE
--cov-fail-under writes a nice message, but dosen't fail the test

### ISSUE THREAD

**Issue by TheoAndersen** [pytest-dev/pytest-cov#233]
I'm trying to use ```cov_fail_under```, which writes a nice 'Fail'-message - but it doesnt fail the tests.

It would be nice if it did also fail the tests - i am especially using logic based on test failure or passing, and am needing to count on this to act as a test-error as well.

**Comment by TheoAndersen** [comment]
Hey, i was too quick.. sorry..

It seems even though the tests report the typical long green bar with "tests passed".. the test-run actually did fail.. and i can rely on that.

Sorry for the confusion

**Comment by blueyed** [comment]
Not looked into this, but if it is confusing it might be worth to improve this.

**Comment by TheoAndersen** [comment]
Actually trying this again, I think it does work. 

It writes “tests passed successfully” but returns a non-0 exit code. 

Sorry i just got confused
