### ISSUE TITLE
pytest-cov doesn't seem to work on Windows 10

### ISSUE THREAD

**Issue by shelldweller** [pytest-dev/pytest-cov#249]
After installing `pytest-cov` on Windows 10, pytest stops working. Any pytest command (even `pytest --help`) stalls forever. After running `pip uninstall pytest-cov` everything is back to normal.

When I run `python -v -m pytest` I get this far:
```
...
import 'pytest_cov' # <_frozen_importlib_external.SourceFileLoader object at 0x000001FBD0B18588>
```
And then it sits there forever. I tried installing an earlier version (2.5.1) - same result.

Versions I have:
coverage==4.5.2
pytest==4.0.1
pytest-cov==2.6.0

**Comment by pafiedor** [comment]
Same issue here, although for me it does work after downgrading to pytest-cov 2.5.1

python==3.6.7
coverage==4.5.2
pytest==4.0.2
pytest-cov==2.6.0

**Comment by shelldweller** [comment]
It appears this issue related to how Python is installed. I can replicate it on system-wide installation (when pytest-cov is installed from admin console). However, when running in venv, there are no issues.
