### ISSUE TITLE
huge dependency change between 2.6.0 and 2.6.1

### ISSUE THREAD

**Issue by smarie** [pytest-dev/pytest-cov#257]
In 2.6.1 pytest version >=3.6 is required, it was not the case in 2.6.0.

This made three of my [pytest plugin projects](https://github.com/smarie/OVERVIEW#tests) builds fail simultaneously yesterday :) indeed their Travis build matrix tests compliance with pytest 2.x and 3.x. 

Of course it is not a bad thing to use the latest versions available, my comment is just about the very hazardous choice of using a "patch" version number increment for such huge change.

(No action is required from this ticket, I now use hardcoded `pytest-cov` versions in my builds. You can close this after reading :) )

**Comment by blueyed** [comment]
Thanks for letting us know.
This was done in https://github.com/pytest-dev/pytest-cov/pull/253, and it wouldn't have been hard to not require this after all.
So if you think it's worth it you could revert this bump and support the old API with older pytest versions I guess.

**Comment by ionelmc** [comment]
Dully noted, we'll do a minor version change when we mess with constraints.

But one has to wonder why someone would bump pytest-cov but not pytest's version :)

**Comment by smarie** [comment]
Thanks for the fast feedback !

**Comment by blueyed** [comment]
https://github.com/pytest-dev/pytest-cov/pull/264 reverts this.
