### ISSUE TITLE
Difference in branch coverage for list comprehensions between Python 2.7 and Python 3.6

### ISSUE THREAD

**Issue by lexotero** [pytest-dev/pytest-cov#258]
Running the same test with the same version of `pytest` and `pytest-cov` but with Python 2.7 and with Python 3.6 produces different report of branch coverage when the source code contains list comprehensions.

I expected to see the same report but it seems that the report when running with Python 2.7 does not consider list comprehensions as a branch and Python 3.6 does.

**Versions**

- Python 2.7.15 and Python 3.6.6
- `pytest` 4.0.2
- `pytest-cov` 2.6.0

**Reproduction steps**

1. Create two virtualenvs, one with Python 2.7 and other with Python 3.6.
2. Install `pytest` 4.0.2 and `pytest-cov` 2.6.0 in both virtualenvs.
3. Create the files described bellow.
4. Run the `pytest` command (also bellow) twice, once in every virtualenv. Make sure you produce coverage reports with different names for each virtualenv.

**Code**

A simple code to reproduce it:

`even_number.py`

```python
from __future__ import absolute_import, division, print_function, unicode_literals                                                                                                                                 


def even_numbers():
    even_numbers = [number for number in range(0, 10) if number % 2 == 0]
    return even_numbers
```

`test_even_number.py`

```python
from __future__ import absolute_import, division, print_function, unicode_literals

from even_numbers import even_numbers


class TestEvenNumbers(object):

    def test_even_numbers_with_no_args_check_return_even_numbers(self):
        numbers = even_numbers()
        assert numbers == [0, 2, 4, 6, 8]
```

**Command**

```bash
pytest test_even_numbers.py --cov even_numbers --cov-branch --cov-report xml:report-<venv>.xml
```

Make sure the `--cov-report` argument changes for each virtualenv, so you don't overwrite the same file when running the command twice.

**My reports**

```xml
<!-- In Python 2.7 environment -->
<class branch-rate="1" complexity="0" filename="even_numbers.py" line-rate="1" name="even_numbers.py">
  <methods/>
    <lines>
      <line hits="1" number="1"/>
      <line hits="1" number="4"/>
      <line hits="1" number="5"/>
      <line hits="1" number="6"/>
    </lines>
</class>
```

```xml
<!-- In Python 3.6 environment -->
<class branch-rate="1" complexity="0" filename="even_numbers.py" line-rate="1" name="even_numbers.py">
  <methods/>
    <lines>
      <line hits="1" number="1"/>
      <line hits="1" number="4"/>
      <line branch="true" condition-coverage="100% (2/2)" hits="1" number="5"/>
      <line hits="1" number="6"/>
    </lines>
</class>
```

**Comment by ionelmc** [comment]
We don't actually do the complicated tracing stuff in pytest-cov, we just use https://github.com/nedbat/coveragepy - that's be the best place to discuss this quirk.

**Comment by lexotero** [comment]
Indeed, I have tried to run `coverage` directly and I also get the difference in the report:

```bash
coverage run --source even_numbers --branch -m pytest test_even_numbers.py
```

```bash
diff coverage-2.7.xml coverage-3.6.xml
```

```diff
2c2
< <coverage branch-rate="1" branches-covered="0" branches-valid="0" complexity="0" line-rate="1" lines-covered="4" lines-valid="4" timestamp="1547129808105" version="4.5.1">
---
> <coverage branch-rate="1" branches-covered="2" branches-valid="2" complexity="0" line-rate="1" lines-covered="4" lines-valid="4" timestamp="1547129761045" version="4.5.1">
16c16
<                                               <line hits="1" number="5"/>
---
>                                               <line branch="true" condition-coverage="100% (2/2)" hits="1" number="5"/>
```

I will report the issue directly in the `coverage` package. Thanks for your help!

**Comment by blueyed** [comment]
I could imagine that this is just a limitation of py2.

**Comment by lexotero** [comment]
I have reduced the example to the bare minimum and reported the issue with the `coverage` package https://github.com/nedbat/coveragepy/issues/753.
