### ISSUE TITLE
--cov-fail-under support float values

### ISSUE THREAD

**Issue by hulucc** [pytest-dev/pytest-cov#260]

**Comment by nedbat** [comment]
Can you say more about why you want float values? Are you trying to set it to 89.7 instead of 89?

**Comment by hulucc** [comment]
Yes. Our team is trying to increase coverage gently. So we want to do something like adding 0.1% per week.

**Comment by mgaitan** [comment]
This is very important because 0.1% could be a quite significant (as in size) piece of code in big projects, and poor coverage may keep hidden in this threshold coefficient truncation.

**Comment by adamzev** [comment]
I don't use `--cov-fail-under` but was hoping for a flag to use to just display increased decimal precision of what our coverage percent is for similar reasons.

**Comment by graingert** [comment]
> I don't use `--cov-fail-under` but was hoping for a flag to use to just display increased decimal precision of what our coverage percent is for similar reasons.

@adamzev can you create a new issue for that, with your usecase. It might be easier for us to just bump the precision for everyone

**Comment by nedbat** [comment]
@adamzev coverage.py already has a setting for the precision to use when it displays results: `[report] precision` https://coverage.readthedocs.io/en/v4.5.x/config.html#report
