### ISSUE TITLE
pytest-cov causes pytest to hang after completing all tests

### ISSUE THREAD

**Issue by BoPeng** [pytest-dev/pytest-cov#261]
After a great deal of detective work, we figured out why our tests fail to exit after they appear to be completed on travis. In summary,

1. With `coverage-cov` 2.6 installed, our test would hang after `pytest` exits.
2. The problem appears even if we use normal [`python test.py`](https://github.com/vatlab/SoS/issues/1196#issuecomment-458609062) when `pytest` is not used.
3. pytest exits normally with `pytest-cov` uninstalled.
4. The problem was found in travis VM but we could reproduce it locally after installing `pytest-cov`.

The program being tested uses multiprocessing, but the processes exit normally. I am reporting the problem here and try to figure out

1. What has caused the tests to hang after pytest exits?
2. Why `pytest-cov` affects normal python unit tests when they are not triggered by `pytest`?

Edit:

To reproduce the problem

1. Install python 3.6+, then `pip install sos`
2. Save the test script [`here`](https://github.com/vatlab/SoS/issues/1196#issuecomment-458609062) in a file, say, `test.py`.
3. Run `python test.py` or `pytest test.py` should pass
4. Install `pytest-cov`
5. `python test.py` or `pytest test.py` will hang

**Comment by ionelmc** [comment]
Also, please do this:
```
try:
    from pytest_cov.embed import cleanup_on_sigterm
    cleanup_on_sigterm()
except ImportError:
    pass

``` 
instead of this:
```
try:
    from pytest_cov.embed import cleanup_on_sigterm
    cleanup_on_sigterm()
except:
    pass
```

In case something is broken inside pytest-cov it shouldn't be hidden.

**Comment by BoPeng** [comment]
Many thanks for your quick response. I can confirm that #262 fixes the issue.
