### ISSUE TITLE
Option to hide terminal coverage report on test failure

### ISSUE THREAD

**Issue by bluenote10** [pytest-dev/pytest-cov#275]
This is a feature request related to the term/term-missing reporters. In general I would like to use

```
addopts =
    --cov=myproject --cov-report term-missing
```

so that co-developers automatically see coverage stats on stdout. However, for big projects, the coverage reports fills more than an entire page on the screen. In case all tests were successful this is fine, because here the coverage is the most relevant information for the developer. However, if a test fails, coverage isn't so relevant and the user has to scroll back up to get information on the failed test. This can get annoying to the point that I often turn off the reporter during development.

It would be nice to have the option to report coverage to terminal only in the success case.

**Comment by ionelmc** [comment]
Worth considering this in https://github.com/pytest-dev/pytest-cov/pull/199

Would a `--cov-report-disable` solve it for you?

**Comment by bluenote10** [comment]
> Would a --cov-report-disable solve it for you?

Not really, because I don't know before running the tests whether it will be successful (and I want to see coverage reports) or whether a test will fail (and I want to omit coverage information). That's also why enabling/disabling the `addopts` option all the time gets annoying.

**Comment by ionelmc** [comment]
@bluenote10 so it turns out there's `--no-cov-on-fail` - doesn't that solve your problem?

**Comment by blueyed** [comment]
Assuming `--no-cov-on-fail` is what is wanted here.

**Comment by bluenote10** [comment]
Exactly what I was looking for, I simply didn't find it in the documentation.
