### ISSUE TITLE
Abort Error Msg

### ISSUE THREAD

**Issue by LienM** [pytest-dev/pytest-cov#292]
Every since installing pytest-cov, whenever I try to run pytest I get the following error msg:

```
(develop) ➜  event-tracking-api git: pytest tests/
============================================================================================================================== test session starts ==============================================================================================================================
platform darwin -- Python 3.7.3, pytest-4.5.0, py-1.8.0, pluggy-0.11.0
rootdir: ~/code/event-tracking-api
plugins: cov-2.7.1
collecting ... [1]    47787 abort      pytest tests/

```

I have no idea why. Ive tried:

pytest tests/
pytest
pytest --no-cov.

All of the result in the same "abort" message. Any ideas why?

**Comment by LienM** [comment]
Update: I made a new virtualenv containing only the dependencies I absolutely needed to run the tests.

(clean-test) ➜  event-tracking-api git:(feature/VTMGO-140_fix_gtm_parsing) pytest
============================================================================================================================== test session starts ==============================================================================================================================
platform darwin -- Python 3.7.3, pytest-4.5.0, py-1.8.0, pluggy-0.11.0
rootdir: /Users/lienmichiels/Froomle/code/event-tracking-api
collecting ... [1]    48120 abort      pytest
(clean-test) ➜  event-tracking-api git:(feature/VTMGO-140_fix_gtm_parsing) pip freeze
atomicwrites==1.3.0
attrs==19.1.0
cachetools==3.1.0
certifi==2019.3.9
chardet==3.0.4
Click==7.0
clickclick==1.2.2
connexion==2.2.0
Flask==1.0.2
Flask-Cors==3.0.7
froomle-events-api==1.1.0.dev1
froomlelogger==0.1.0
google-api-core==1.10.0
google-auth==1.6.3
google-cloud-pubsub==0.40.0
googleapis-common-protos==1.5.10
grpc-google-iam-v1==0.11.4
grpcio==1.20.1
idna==2.8
inflection==0.3.1
itsdangerous==1.1.0
Jinja2==2.10.1
jsonschema==2.6.0
MarkupSafe==1.1.1
more-itertools==7.0.0
openapi-spec-validator==0.2.6
pathlib==1.0.1
pluggy==0.11.0
protobuf==3.7.1
py==1.8.0
pyasn1==0.4.5
pyasn1-modules==0.2.5
pytest==4.5.0
pytz==2019.1
PyYAML==5.1
requests==2.21.0
rsa==4.0
six==1.12.0
swagger-ui-bundle==0.0.3
urllib3==1.24.3
uWSGI==2.0.17.1
wcwidth==0.1.7
Werkzeug==0.15.2

This has always worked before 🤷‍♂

**Comment by ionelmc** [comment]
Does that happen right away or it's stuck for a while before you get the abort message?

**Comment by LienM** [comment]
It happens pretty much right away ~1/2 secs. I had a colleague try the same thing and he actually gets the coverage report as expected on the same repo. 

Is there a way I could inspect what caused the error in more detail?

**Comment by ionelmc** [comment]
Trace the processes, use something like `dtruss -f pytest`. Redirect to a file and attach it, or just paste the part that seems relevant.

**Comment by LienM** [comment]
@ionelmc Thanks so much for your help. Turns out it had something to do with a bug in the logger we use. I'll close this issue.

Sorry to have bothered you and thanks again for your assistance! Much appreciated.
