### ISSUE TITLE
Skip coverage for a unittest

### ISSUE THREAD

**Issue by artgoldberg** [pytest-dev/pytest-cov#296]
I need to change the working directory to run a unit test. This generates an INTERNALERROR in pytest/pytest-cov. Is it possible to decorate the unittest so coverage is turned off while the test is run?

Thanks
Arthur

**Comment by artgoldberg** [comment]
More specifically, running this test:

    def test_migrate_data(self):    # pragma: no cover
        # working directory must be in test_repo
        os.chdir(test_repo_copy.repo_dir)

with this command

    pytest  -s   --cov=obj_model/ --cov-branch tests/test_migrate.py::TestCementControllers::test_migrate_data

produces this error

    INTERNALERROR> Traceback (most recent call last):
    INTERNALERROR>   File "/usr/local/lib/python3.6/site-packages/_pytest/main.py", line 178, in wrap_session
    INTERNALERROR>     session.exitstatus = doit(config, session) or 0
    INTERNALERROR>   File "/usr/local/lib/python3.6/site-packages/_pytest/main.py", line 215, in _main
    INTERNALERROR>     config.hook.pytest_runtestloop(session=session)
    INTERNALERROR>   File "/usr/local/lib/python3.6/site-packages/pluggy/hooks.py", line 258, in __call__
    INTERNALERROR>     return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
    INTERNALERROR>   File "/usr/local/lib/python3.6/site-packages/pluggy/manager.py", line 67, in _hookexec
    INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
    INTERNALERROR>   File "/usr/local/lib/python3.6/site-packages/pluggy/manager.py", line 61, in <lambda>
    INTERNALERROR>     firstresult=hook.spec_opts.get('firstresult'),
    INTERNALERROR>   File "/usr/local/lib/python3.6/site-packages/pluggy/callers.py", line 196, in _multicall
    INTERNALERROR>     gen.send(outcome)
    INTERNALERROR>   File "/usr/local/lib/python3.6/site-packages/pytest_cov/plugin.py", line 228, in pytest_runtestloop
    INTERNALERROR>     self.cov_controller.finish()
    INTERNALERROR>   File "/usr/local/lib/python3.6/site-packages/pytest_cov/engine.py", line 167, in finish
    INTERNALERROR>     self.cov.stop()
    INTERNALERROR>   File "/usr/local/lib/python3.6/site-packages/coverage/control.py", line 675, in load
    INTERNALERROR>     self._init()
    INTERNALERROR>   File "/usr/local/lib/python3.6/site-packages/coverage/control.py", line 223, in _init
    INTERNALERROR>     set_relative_directory()
    INTERNALERROR>   File "/usr/local/lib/python3.6/site-packages/coverage/files.py", line 28, in set_relative_directory
    INTERNALERROR>     RELATIVE_DIR = os.path.normcase(abs_file(os.curdir) + os.sep)
    INTERNALERROR>   File "/usr/local/lib/python3.6/site-packages/coverage/files.py", line 163, in abs_file
    INTERNALERROR>     path = os.path.realpath(path)
    INTERNALERROR>   File "/usr/local/lib/python3.6/posixpath.py", line 389, in realpath
    INTERNALERROR>     return abspath(path)
    INTERNALERROR>   File "/usr/local/lib/python3.6/posixpath.py", line 376, in abspath
    INTERNALERROR>     cwd = os.getcwd()
    INTERNALERROR> FileNotFoundError: [Errno 2] No such file or directory

whereas running this command

    pytest  -s  tests/test_migrate.py::TestCementControllers::test_migrate_data

passes the test.

Thanks, Arthur

**Comment by blueyed** [comment]
You should probably use `monkeypatch` to change the dir only during the test.. looks like coverage crashes due to the cwd being changed.

**Comment by blueyed** [comment]
I.e. it is not really related to using coverage there in the first place, but bad practice in general.
(IIRC there is a `no_cov` or similar fixture though)

**Comment by artgoldberg** [comment]
Good point. I can just restore the cwd at the end of the test in `finally:`. Thanks.
