### ISSUE TITLE
\n in regex is not recognized by exclude_lines

### ISSUE THREAD

**Issue by dmcnulla** [pytest-dev/pytest-cov#297]
I'm trying to skip the entire main for coverage. But I can't figure out what the regex should be. 
from setup.cfg
```
[report]
exclude_lines = if __name__ == .__main__.\:.*(\n.*)+
```

code
```
def whatever():
	return 1
	
if __name__ == "__main__":
	print(whatever())
```
The print statement always show as not being covered. Hopefully I'm just doing it wrong.
I've also tried `exclude_lines = if __name__ == .__main__.\:.*\n.*` which didn't work.
And I verified both in a [regex tester](https://regexr.com/)

**Comment by ionelmc** [comment]
I suspect you cannot have new lines in there (eg: regex would be applied to individual lines). Try some of the examples from: https://coverage.readthedocs.io/en/v4.5.x/excluding.html?highlight=exclude_line ?

Either way, if you have indeed have found a bug you should report it in https://github.com/nedbat/coveragepy/ not here (pytest-cov merely wraps coveragepy).
