### ISSUE TITLE
Combine multiple xml report

### ISSUE THREAD

**Issue by pankajmalhotra** [pytest-dev/pytest-cov#300]
I am running pytest and generating xml report. Is there a way I can combine all the xml report?
example:
pytest --cov=. --cov-report=xml:report1.xml
pytest --cov=. --cov-report=xml:report2.xml

Is it possible to combine report1.xml and report2.xml?

**Comment by blueyed** [comment]
I think you have to append coverage first, and then only generate the report in the end:
```
pytest --cov=. --cov-append
pytest --cov=. --cov-report=xml:report2.xml
```

**Comment by ionelmc** [comment]
I think the question has been addressed sufficiently.
