### ISSUE TITLE
Decorator Function marked as Missed

### ISSUE THREAD

**Issue by psdon** [pytest-dev/pytest-cov#301]
pytest-cov always missed Decorator Functions from submodules

------------------------------
setup.cfg
> [tool:pytest]
testpaths = tests
addopts = --cov=app --cov-report html --driver Firefox --driver-path ./geckodriver

**Comment by ionelmc** [comment]
@psdon sorry for lateness here but can you post some reproducing details?

**Comment by fscherf** [comment]
@psdon 
Hi! I have the same problem.
https://codecov.io/gh/pengutronix/flamingo/src/master/flamingo/pytest.py
To reproduce clone www.github.com/pengutronix/flamingo and run "tox"

**Comment by ionelmc** [comment]
@fscherf it looks like you have a pytest plugin in there, does this fix it for you https://github.com/pytest-dev/pytest/issues/935#issuecomment-478388199 ?

**Comment by fscherf** [comment]
@ionelmc 
No, i tried that before

**Comment by ionelmc** [comment]
@fscherf ah ... looks like we still need the old preloading technique. See https://pytest-cov.readthedocs.io/en/latest/plugins.html

**Comment by psdon** [comment]
@fscherf 

> looks like we still need the old preloading technique. See https://pytest-cov.readthedocs.io/en/latest/plugins.html

This does not fix the problem

**Comment by ionelmc** [comment]
@psdon you still haven't posted a reproducer :)

**Comment by psdon** [comment]
Closing this issue. Using Tox worked magically.
