### ISSUE TITLE
Concurrency option support

### ISSUE THREAD

**Issue by KHN190** [pytest-dev/pytest-cov#303]
I was running coverage with a `--concurrency` option to correctly cover eventlet related code:

```bash
$coverage --concurrency=eventlet run all_tests.py
```

But after I switched to pytests, I don't see the option is provided anymore. And some coverage is missing. Is this a missing feature?

**Comment by blueyed** [comment]
You can use the coverage config file, e.g. `.coveragerc` for this.

**Comment by KHN190** [comment]
@blueyed Thanks this solved the problem. I'm closing it.
