### ISSUE TITLE
--cov-fail-under support number of missed statements

### ISSUE THREAD

**Issue by Seirdy** [pytest-dev/pytest-cov#309]
Currently, the only way to specify a coverage threshold for passing is with a percentage. This has one drawback: when removing code that meets/exceeds the threshold, the total number of statements in a project decreases, thereby decreasing the project's code coverage *even though no additional statements were missed.* It doesn't make sense for tests to switch from passing to failing if no new statements were missed.

Measuring coverage by the number of missed statements instead of a percentage will not cause deletion of covered code to fail tests.

**Comment by blueyed** [comment]
Sounds like something that should be provided via coverage.py.

But in general I'd just ignore the drop, or actually require to cover some previously uncovered code (to make deleting less fun ;)).

**Comment by Seirdy** [comment]
Thing is, pytest can already report the number of missed statements as well as the percentage in the terminal coverage report generated at the end, so it should be possible to use that instead of a percentage to fail tests.

See for example https://gitlab.com/Seirdy/func-analysis/-/jobs/249289138; Pytest reports exactly which three statements were missed. Pytest-cov shouldn't cause my pipeline to fail as long as those statements don't change.

**Comment by Zac-HD** [comment]
See upstream issue https://github.com/nedbat/coveragepy/issues/815
