### ISSUE TITLE
Confusing behaviour with any(…) and a generator

### ISSUE THREAD

**Issue by alexwlchan** [pytest-dev/pytest-cov#310]
Consider the following example test:

```python
# repro.py

basket = ["apple", "banana", "cherry"]

def test_basket_contains_b():
    assert any("b" in fruit for fruit in basket)
```

```ini
# .coveragerc
[run]
branch = True

[report]
show_missing = True
```

If I run this test under pytest-cov, and print a report, it tells me that `8->exit` isn’t covered:

```console
$ pytest --cov=repro repro.py ; coverage report
[…]
Name       Stmts   Miss Branch BrPart  Cover   Missing
------------------------------------------------------
repro.py       3      0      2      1    80%   8->exit
```

If I wrap the generator comprehension in a list, coverage is happy:

```python
    assert any(["b" in fruit for fruit in basket])
```

If I run the body of that function under plain coverage, it doesn't complain, so it looks like this is something to do with the interactions with py.test?

```console
$ cat repro2.py
basket = ["apple", "banana", "cherry"]

assert any(["b" in fruit for fruit in basket])

$ coverage run repro2.py

$ coverage report
Name       Stmts   Miss Branch BrPart  Cover   Missing
------------------------------------------------------
repro2.py      2      0      2      0   100%
```

I'm not sure if this is a bug per se, and it's not blocking my work – I can wrap my `any(…)` calls with a list – but it was confusing, and I thought it worth flagging the discrepancy between vanilla coverage and pytest-cov.

### Setup

Python 3.7.2 running on macOS. pytest-cov 2.7.1. I'm running in a fresh virtualenv with these dependencies:

```console
$ pip freeze
atomicwrites==1.3.0
attrs==19.1.0
coverage==4.5.3
importlib-metadata==0.18
more-itertools==7.2.0
packaging==19.0
pluggy==0.12.0
py==1.8.0
pyparsing==2.4.0
pytest==5.0.1
pytest-cov==2.7.1
six==1.12.0
wcwidth==0.1.7
zipp==0.5.2
```

### Duplicates

I tried to look for existing bug reports, but "any" is such a common keyword I couldn't find anything useful.

**Comment by blueyed** [comment]
Thanks for the detailed report!
It looks like an issue with pytest rather than pytest-cov, when comparing it directly to coverage.py though (you do not use `coverage -m pytest …` there to not use pytest-cov).

**Comment by alexwlchan** [comment]
For extra bonus funsies: the following code also gets a complaint about a missing branch, even though all I’ve changed is whitespace:

```python
basket = ["apple", "banana", "cherry"]

def test_basket_contains_b():
    assert any([
        "b" in fruit for fruit in basket
    ])
```

**Comment by ionelmc** [comment]
Must be the assertion rewriter adding something that looks like a branch. The way I see it you're missing a test for empty basket :)

**Comment by alexwlchan** [comment]
@ionelmc My fruit basket is never empty. ;)

**Comment by software-dov** [comment]
Ran into this just now on debian 4.19.37, python3.6, running in a fresh virtualenv via nox, with `next`:

Minimal reproducible example
```
from collections import namedtuple
Element = namedtuple("Element", ["key", "val"])
elements = [
    Element("squid", "teuthida"),
    Element("clam", "tridacna"),
    Element("whelk", "buccinoidea")
]
squid = next(e.val for e in elements if e.key == "squid")
```

**Comment by blueyed** [comment]
This is not specific to pytest-cov.

Given t_any.py:
```python
from collections import namedtuple


def test():
    Element = namedtuple("Element", ["key", "val"])
    elements = [
        Element("squid", "teuthida"),
        Element("clam", "tridacna"),
        Element("whelk", "buccinoidea")
    ]
    squid = next(e.val for e in elements if e.key == "squid")


if __name__ == "__main__":
    test()
```

`coverage run --rcfile=/dev/null --branch t_any.py; coverage report t_any.py` reports:
```
t_any.py       7      0      4      2    81.82%   11->exit, 14->exit
```

With `pytest --cov=t_any --cov-config=/dev/null --cov-branch --cov-report=term-missing t_any.py`:
```
t_any.py       7      1      4      2    73%   15, 11->exit, 14->15
```

Line 15 is the last one - the call to the test function when not using pytest.

**Comment by blueyed** [comment]
Going through duplicates in coveragepy's issues I've landed at https://github.com/nedbat/coveragepy/issues/515.

But using `--assert=plain` with `pytest` still results in `15, 11->exit, 14->15`.

So it's really an issue with coverage.py.

(Coverage.py, version 4.5.2 with C extension, This is pytest version 4.3.0, Python 3.7.4 - apparently an old venv I have there for pytest-cov ;))
