### ISSUE TITLE
Support for dynamic contexts

### ISSUE THREAD

**Issue by sidps** [pytest-dev/pytest-cov#312]
Coverage.py supports [dynamic contexts](https://coverage.readthedocs.io/en/latest/contexts.html#dynamic-contexts).

However, setting those options in `.coveragerc`, while using with the `pytest-cov` plugin, throws errors like so:
```
coverage.misc.CoverageException: Unrecognized option '[run] dynamic_context=' in config file .coveragerc
```

**Comment by blueyed** [comment]
Make sure to use coverage.py 5 then there also (with pytest-cov).

See https://github.com/pytest-dev/pytest-cov/pull/283 for more discussion on the feature, and https://github.com/pytest-dev/pytest-cov/pull/291 for testing with coverage.py 5.

Closing, but feel free to re-open / followup of course.
