### ISSUE TITLE
Coverage report run under docker reports incorrect source

### ISSUE THREAD

**Issue by mcaulifn** [pytest-dev/pytest-cov#329]
I am attempting to generate a coverage report for SonarQube. The project is built and tested using a container. The xml file has the source listed `<source>/build/project</source>` where as the actual files are under `/data/jenkins/workspace/project/lambda`. Is there a way to re-write the source when generating the report? python and libraries are not available outside the container as this is a Jenkins instance.

**Comment by ionelmc** [comment]
Did you try the aliasing options here https://coverage.readthedocs.io/en/v4.5.x/config.html#paths ?

**Comment by mcaulifn** [comment]
Yes, in the `.coveragec` file (/data/jenkins/workspace/project/lambda/), I put the following:

```
[paths]
source =
    project/
    /build/*
```

Nothing had changed in the report.

**Comment by mcaulifn** [comment]
@ionelmc any update?

**Comment by ionelmc** [comment]
So you're generating the report outside the running container? That means you're not using pytest-cov for that. How is that a pytest-cov problem?

**Comment by mcaulifn** [comment]
the report is generated inside the container. it is not valid outside the container because the paths are different.

**Comment by ionelmc** [comment]
I'm afraid you need to have the sources in the actual path inside the container, unless I misunderstood how coveragepy works. Either way this ain't a bug in pytest-cov.

You could also apply a XSLT the the coverage.xml, in addition to mounting an extra path inside the cotainer.

**Comment by nedbat** [comment]
@mcaulifn You should open an feature request against coverage.py: when it generates the XML report, it uses the filenames as it knows them. In your case, those are names inside the container.

**Comment by mcaulifn** [comment]
closing in favor of https://github.com/nedbat/coveragepy/issues/597
