### ISSUE TITLE
exclude coverage report from command line?

### ISSUE THREAD

**Issue by SHxKM** [pytest-dev/pytest-cov#355]
Everytime I invoke pytest from the command-line:

```
pytest -k "some_example"
```

My coverage report is reset to reflect that only tests matching "some_example" are covered. This is understandable given my `pytest.ini` file:

```ini
addopts = --cov=. --cov-report=html
```

How can I keep the settings in my `ini` but still have the ability to skip `cov` on-demand?

**Comment by nedbat** [comment]
From the help text: "Use --cov-report= to not generate any output."
