### ISSUE TITLE
Coverage report missed «import time» statements on pytest plugin project

### ISSUE THREAD

**Issue by pohmelie** [pytest-dev/pytest-cov#359]
I write a plugin for pytest. Register it with `pytest` entrypoint in my setup.cfg file. Wrote some tests which works as expected, but coverage report shows that missed lines are those which evaluates at import time (decorators, `def`, `async def`, imports, etc.).  
AFAIR, since this is a plugin for pytest and it is actually installed (in editable mode `-e`) import happens on pytest load and not counts by coverage plugin.  
I hope this is known problem and there is an easy solution, since other plugin projects works somehow with coverage.

**Comment by ionelmc** [comment]
Take a look at https://pytest-cov.readthedocs.io/en/stable/plugins.html

**Comment by pohmelie** [comment]
Ok, got it. Thank you for fast response.
