### ISSUE TITLE
Fix CI

### ISSUE THREAD

**Issue by blueyed** [pytest-dev/pytest-cov#365]
CI is currently broken.

One of the main reasons might be https://github.com/pytest-dev/pytest-xdist/pull/448#discussion_r330989777, but it looks like there is more.

This is meant to keep track of issues in this regard, and IMHO should have high priority, since it makes even trivial PRs unnecessarily "red" / failing, and even the latests PRs and releases have been done with red CI.

**Comment by ionelmc** [comment]
Ooooof. Well, there are 2 nasty things going on that take time to figure out:

1. The xdist problem from https://github.com/pytest-dev/pytest-xdist/pull/448#discussion_r330989777 - we either drop support for un-collocated mode (ssh/popen xdist) or spend time debugging.

2. Python3.8's multiprocessing is broken (well, more than the usual multiprocessing being architecturally broken) - there's a simple reproducer in https://bugs.python.org/issue38227 

I guess we can drop the ball and skip multiprocessing tests on 3.8 and advise users to stop using garbage like multiprocessing? Or spend tons of time debugging.

I guess we could try the technique in https://github.com/nedbat/coveragepy/blob/master/coverage/multiproc.py but I doubt it would be as reliable.

**Comment by blueyed** [comment]
> advise users to stop using garbage like multiprocessing

Can you elaborate?  I've thought about using it with / adding it to pytest by default, and there's a WIP for xdist also to use it (https://github.com/pytest-dev/pytest-xdist/pull/479).
What would you recommend instead?

**Comment by ionelmc** [comment]
Multiprocessing is over-engineered. It's the inevitable result of trying to produce something that works on all platforms. Read the sourcecode and shudder in horror :)

It's also maintained badly - the response in the cpython bugtracker is simply disappointing.

So I wouldn't use it for those two reasons.

**Comment by ionelmc** [comment]
Good news everyone: the xdist problem is going to be fixed with a new xdist release.

Regarding the python 3.8 problem ... I guess we could just make the signal setup be no-op on python3.8 and skip tests for now?
