### ISSUE TITLE
Branch coverage on `continue` statement

### ISSUE THREAD

**Issue by ludaavics** [pytest-dev/pytest-cov#368]
Not sure if this is a feature or a bug, but the following snippet reports `3->5` as missing coverage  ...
```python
def my_func(x):
    for i in range(10):
        if i > 3:
            print("Doing some work")
        continue


# in the test suite
import foo

def test_foo():
    bar = foo.my_func(5)
```

... while the following code gives 100% branch test coverage
```python
def my_func(x):
    for i in range(10):
        if i > 3:
            print("Doing some work")
        print("Doing nothing")
        continue
```

I realize the example above is a bit contrived, since there is nothing after the `continue`, but seems like the first snippet should have full test coverage?

It seems there is something about the no-op statements, since the following also report missing coverage:

```python
def my_func(x):
    for i in range(10):
        if i > 3:
            print("Doing some work")
        pass
```

**Comment by nedbat** [comment]
This is because of coverage.py bug https://github.com/nedbat/coveragepy/issues/198, which is really a Python issue. There's nothing pytest-cov can do about it.
