### ISSUE TITLE
Example in docs does not paste

### ISSUE THREAD

**Issue by kpinc** [pytest-dev/pytest-cov#375]
Hello,

The example command line in:
https://pytest-cov.readthedocs.io/en/latest/plugins.html

does not paste.  The double dashes are converted
to some sort of unicode codepoint.

I have not looked elsewhere in the docs to see if
there are other similar problems.

**Comment by nedbat** [comment]
Thanks, fixed in b5d092f74d58c40ace4912078abf262268575bb2
