### ISSUE TITLE
option to silence coverage console output

### ISSUE THREAD

**Issue by ssbarnea** [pytest-dev/pytest-cov#389]
While we want to produce coverage reports we do not want to display anything on console about them. At this moment I seen no option for silenting coverage execution , I always get something like:

```
---------- coverage: platform darwin, python 2.7.16-final-0 ----------
Coverage XML written to file /Users/ssbarnea/c/os/molecule/.tox/py27-ansible28-unit/log/coverage.xml
```

I am not if that this counts as a feature request or a request to document a feature but any help would be appreciated. Thanks.

**Comment by nedbat** [comment]
If you produce no reports with pytest-cov, and instead use a separate coverage command to do them, then you can control the output more precisely.  Let's please not add more code to pytest-cov to control this output.

**Comment by nedbat** [comment]
There's no reason you need to use pytest-cov to produce the reports at all.  Run the tests with pytest-cov to collect the data.  Then use `coverage report` to report on the results. Then you can control each command's output individually.
