### ISSUE TITLE
pytest-cov doesn't read pyproject.toml as coverage config

### ISSUE THREAD

**Issue by frostming** [pytest-dev/pytest-cov#390]
# Summary

## Expected vs actual result

Read pyproject.toml as converage.py does.

# Reproducer

## Versions

Output of relevant packages `pip list`, `python --version`, `pytest --version` etc.

Make sure you include complete output of `tox` if you use it (it will show versions of various things).

## Config

Include your `tox.ini`, `pytest.ini`, `.coveragerc`, `setup.cfg` or any relevant configuration.

## Code

Link to your repository, gist, pastebin or just paste raw code that illustrates the issue.

If you paste raw code make sure you quote it, eg:

```python
def foobar():
    pass
```

**Comment by nedbat** [comment]
I don't think pytest-cov has preconceptions about the possible configuration files.  Are you sure you installed the "coverage[toml]" extra?

**Comment by frostming** [comment]
Sorry, I installed `tomlkit` so I thought I have done that.

**Comment by kingbuzzman** [comment]
Having this exact issue now. 

```
coverage            7.0.5
pytest              7.2.1
pytest-cov          4.0.0

$ pip install coverage[toml]
Requirement already satisfied: coverage[toml] in /usr/local/lib/python3.8/site-packages (7.0.5)
Requirement already satisfied: tomli in /usr/local/lib/python3.8/site-packages (from coverage[toml]) (2.0.1)
```

* `python -W ignore -m pytest --no-migrations --cov . --cov-report xml && coverage report -m` ignores all my pyproject.toml settings
* `python -W ignore -m pytest --no-migrations --cov . ` same outcome as above
* `python -W ignore -m coverage run /usr/local/bin/pytest --no-migrations` works as expected.

**Comment by zyv** [comment]
I'm having the same problem here:

https://github.com/zyv/pilot_log/actions/runs/8724935482/job/23936694801

```
platform linux -- Python 3.11.9, pytest-8.1.1, pluggy-1.4.0
django: version: 5.0.4, settings: config.settings (from ini)
configfile: pyproject.toml
plugins: requests-mock-1.12.1, cov-5.0.0, django-4.8.0
```

Any idea?
