### ISSUE TITLE
Does pytest-cov follow semver?

### ISSUE THREAD

**Issue by alvassin** [pytest-dev/pytest-cov#392]
Does this package use [semantic versioning](https://semver.org) ([PEP 440](https://www.python.org/dev/peps/pep-0440/#semantic-versioning))? 
Is it safe to use ~= requirement operator?
```
pytest-cov~=2.8.1
```

**Comment by ionelmc** [comment]
It should be fine. Historically minor releases had mostly unintentional breaking changes but patch releases should be safe.

**Comment by alvassin** [comment]
Thank you for fast response! 
So, it is ok for `pytest-cov~=2.8.1`, but may break code for `pytest-cov~=2.8`, right?

**Comment by ionelmc** [comment]
Yes, use `pytest-cov~=2.8.1`.
