### ISSUE TITLE
How could pytest-cov's xml report contains “methods” keyword？

### ISSUE THREAD

**Issue by leafonsword** [pytest-dev/pytest-cov#394]
I use pytest-cov's xml report to combine with jenkins and Cobertura to generate code coverage rate, and command is `pytest -v --cov=app/controllers/p0_basement/  --cov-report=xml ci_api_test.py`~

But Java and maven's xml report contains 6 indexes:
![image](https://user-images.githubusercontent.com/1754580/76185833-6791eb80-620b-11ea-9067-1394f26e527e.png)

While Python and pytest-cov's xml report just contains 5 indexes:
![image](https://user-images.githubusercontent.com/1754580/76185996-e0914300-620b-11ea-82e7-eaa5958243a4.png)

So could  pytest-cov's xml report contains “methods” keyword？

**Comment by nedbat** [comment]
The XML report is made by https://github.com/nedbat/coveragepy, you should check the issues there.
