### ISSUE TITLE
New release needed to work with latest pytest-xdist

### ISSUE THREAD

**Issue by kbattocchi** [pytest-dev/pytest-cov#422]
# Summary

If I pip install the latest pytest-xdist and pytest-cov, then I will get failures when running `pytest -n auto --cov=<my directory>` because the latest released pytest-cov (2.10.0) is not compatible with pytest-xdist 2.0.0; this has been fixed by #412 but this PR hasn't made it into any release.

## Versions

pytest-xdist 2.0.0
pytest-cov 2.10.0

**Comment by ionelmc** [comment]
I'll cut a release after CI passes.

**Comment by ssbarnea** [comment]
@ionelmc Super, that is great. I may avoid the pining.

**Comment by nicoddemus** [comment]
Thanks @ionelmc, thanks for the quick response!

**Comment by ssbarnea** [comment]
I see that CI is all green, mind to push the magic 2.10.1 tag?

**Comment by ionelmc** [comment]
2.10.1 is released.

**Comment by kbattocchi** [comment]
Thanks for the quick response!

**Comment by shlomiken** [comment]
Hi 
i had the original problem described here - and i upgraded to the 2.10.1 version (working with xdist 2.0.0) 
now i get this error - what am i missing here ?

```
packages/xdist/workermanage.py", line 299, in sendcommand
17:36:59 INTERNALERROR>     self.channel.send((name, kwargs))
17:36:59 INTERNALERROR>   File "/home/centos/workspace/predictive-models-pull-request/rpclick-model/venv/lib/python3.6/site-packages/execnet/gateway_base.py", line 728, in send
17:36:59 INTERNALERROR>     raise IOError("cannot send to {!r}".format(self))
17:36:59 INTERNALERROR> OSError: cannot send to <Channel id=3 closed>
```

**Comment by ionelmc** [comment]
@shlomiken you might want to make a bug report to https://github.com/pytest-dev/pytest-xdist with more details to get the right people see it.

**Comment by shlomiken** [comment]
I was having older version of pytest , now when moved to 6.0 everything is working.
here are the final versions i can confirm working 
```
pytest==6.0.1
pytest-cov==2.10.1
pytest-xdist==2.0.0
```
