### ISSUE TITLE
Multiple -cov-fail-under parameters for separate coverage types

### ISSUE THREAD

**Issue by AgilePlaya** [pytest-dev/pytest-cov#423]
# Summary

If the user is checking for branch coverage, the generated report contain details of branch coverage as well as line coverage. However, only one parameter can be fed for -fail-under, which in this scenario only checks for branch coverage.

It would be better if there could be at most 2 parameters for -fail-under, where the default parameter is still the same but with an extra parameter for line-coverage checking as well.

**Comment by ionelmc** [comment]
Afaik this is not possible at all, coveragepy only records one type of data (either branch or line).
