### ISSUE TITLE
Tearing down a subprocess is not being done smoothly

### ISSUE THREAD

**Issue by alanwilter** [pytest-dev/pytest-cov#431]
This is a spin-off of issue #425 (which is solved).

I got it to work with my main application, but since I want only coverage, I'm not using docker, so I have this:

```python
...
@pytest.fixture(scope="session")
def app_server():
    with TestProcess("python", "application.py") as app_server:
        wait_for_strings(app_server.read, 10, "Running")
        print(app_server.read())
        yield app_server
        print("\n>>>>Teardown app_service")
        app_server.close()

@pytest.fixture(scope="function")
def api(api_url, app_server):
    api = Api(api_url)
    yield api
    for user in list(api.logged_in):
        api.logout(user)
```
so now `test_auth.py` reports 100% covered. However, it's just probably not a critical issue, I got this message at the end:
```
tests/test_views.py::test_create_user PASSED
>>>>Teardown app_service
2020-09-03 18:31:55,457-ERROR-process_tests::process_tests|186:: TestProcess(pid=79236, is_alive=False) failed to cleanup buffers: ValueError('I/O operation on closed file.')
Traceback (most recent call last):
  File "/usr/local/Caskroom/miniconda/base/lib/python3.7/site-packages/process_tests.py", line 174, in __exit__
    data, _ = self.proc.communicate()
  File "/usr/local/Caskroom/miniconda/base/lib/python3.7/subprocess.py", line 951, in communicate
    stdout = self.stdout.read()
ValueError: I/O operation on closed file.
```
Just wondering what `process_tests:TestProcess` is really trying to do/say.

With my basic example model in https://github.com/alanwilter/flask-pytest-example I don't have this problem.

**Comment by ionelmc** [comment]
Still not the right issue tracker but well, I guess the problem there is that the process died while subprocess.Popen.communicate was reading from stdout. Strange yes, only problem I see is possible loss of output. Could even be a python bug.

**Comment by alanwilter** [comment]
Sorry for that, I guess I should have used `python-process-tests` channel.
Anyway, I simply removed line `app_server.close()` and it finishes clear, without any weird messages. I even tried with `gunicorn` and I got only my logger to inform it's killing the server, which is pretty fine. I close this as I'm happy with the results.
