### ISSUE TITLE
Is it possible to write `.coverage` in a specific folder?

### ISSUE THREAD

**Issue by alanwilter** [pytest-dev/pytest-cov#432]
I don't find any documentation about it, so if not possible at the moment, could it be a feature to implement in the future?

I would like to be able to save `.coverage` in a specific folder when running `pytest --cov ...`

**Comment by blueyed** [comment]
Try setting `COVERAGE_FILE` ([ref](https://coverage.readthedocs.io/en/coverage-5.2.1/cmd.html?highlight=coverage_file#data-file)).

**Comment by alanwilter** [comment]
Thanks!
