### ISSUE TITLE
Coverage for file not included

### ISSUE THREAD

**Issue by MatTerra** [pytest-dev/pytest-cov#436]
# Summary

I have a sequence of tests that I run with pytest --cov and the coverage started to show up smaller than expected. One file was being reported with 0% line coverage(should be 100%). The test result showed up in pytest report. 

I run tests with the following command:
 `pytest -p pytest_cov --junitxml=../xunit-reports/xunit-result-nova_api.xml --cov=nova_api --cov-report xml:../coverage-reports/coverage-python.xml unittests`

If I manually included the test file in the command, it gets reported as 100% coverage:
`pytest -p pytest_cov --junitxml=../xunit-reports/xunit-result-nova_api.xml --cov=nova_api --cov-report xml:../coverage-reports/coverage-python.xml unittests/test_postrgresqlhelper.py unittests`

*Order of arguments matter! Adding the file after the module still reports wrong coverage*
   

## Expected vs actual result

It should be detected as covered when pytest is invoked on the module

# Reproducer

See summary

Pytest output:
```
================================================================= test session starts ==================================================================
platform linux -- Python 3.8.5, pytest-6.0.2, py-1.9.0, pluggy-0.13.1
rootdir: NovaAPI/tests, configfile: pytest.ini
plugins: cov-2.10.1, mock-3.1.1, mysql-2.0.1, asyncio-0.12.0, assume-2.2.1, ordering-0.6
collected 245 items                                                                                                                                    

unittests/test_api_utils.py ...........................................                                                                          [ 17%]
unittests/test_auth.py .............                                                                                                             [ 22%]
unittests/test_entity.py .........                                                                                                               [ 26%]
unittests/test_generic_dao.py .........                                                                                                          [ 30%]
unittests/test_generic_sql_dao.py ..................................................                                                             [ 50%]
unittests/test_generic_sql_dao_postgres.py ..................................................                                                    [ 71%]
unittests/test_mysqlhelper.py ............................                                                                                       [ 82%]
unittests/test_mysqlpoll.py .......                                                                                                              [ 85%]
unittests/test_postgresqlhelper.py .............................                                                                                 [ 97%]
unittests/test_postgresqlpoll.py .......                                                                                                         [100%]

=================================================================== warnings summary ===================================================================
# Some test files have classes in them which are used in the test. They have __init__ methods so they appear as warnings

-- Docs: https://docs.pytest.org/en/stable/warnings.html
--------------------- generated xml file: ../xunit-reports/xunit-result-nova_api.xml ----------------------

----------- coverage: platform linux, python 3.8.5-final-0 -----------
Coverage XML written to file coverage.xml

=========================================================== 245 passed, 8 warnings in 6.10s ============================================================
```

## Versions

Output of relevant packages `pip list`, `python --version`, `pytest --version` etc.
pytest                          6.0.2
pytest-cov                    2.10.1
cov-core                      1.15.0
coverage                      5.3
python                          3.8.5

## Config
pytest.ini
```
[pytest]
junit_family=xunit2

```

## Code

https://github.com/novaweb-mobi/nova-api/tree/feature_postgresql

**Comment by ionelmc** [comment]
You should remove `cov-core` - it's no longer required since pytest-cov 2.0 (5 years ago).

As for the problem at hand I suspect you have some side-effects in your test suite (eg: some bad monkeypatching?) because changing the test collection order introduces the problem.

Also, for debugging purposes I would remove the junit xml stuff and just look at the simpler text report to make sure the problem is not in the xml parsing/display side.

**Comment by MatTerra** [comment]
I'll try to run without the junit xml. Could be a side-effect from the mocking, however there is a MySQLHelper class, which is equivalent to the one not being reported that is reported. Seems odd.

**Comment by MatTerra** [comment]
An import in the test class wasn't using the full path. It worked because of the PYTHONPATH set, but wasn't identifying coverage. Closing this issue.
