### ISSUE TITLE
Support coverage context with subprocess calls

### ISSUE THREAD

**Issue by gaborbernat** [pytest-dev/pytest-cov#442]
After coverage starts here https://github.com/pytest-dev/pytest-cov/blob/master/src/pytest_cov/embed.py#L74, we should pull context set from parent process https://github.com/pytest-dev/pytest-cov/blob/master/src/pytest_cov/embed.py#L74 here.

**Comment by ionelmc** [comment]
Both links point to the same line number - not sure what you had in mind. What do you mean "pull"?

**Comment by gaborbernat** [comment]
@ionelmc my bad, here's what I was thinking - https://github.com/pytest-dev/pytest-cov/pull/443, can add tests/etc if you agree.
