### ISSUE TITLE
Set minimum coverage per file

### ISSUE THREAD

**Issue by bazzadp** [pytest-dev/pytest-cov#444]
# Summary

The `--cov-fail-under=MIN` configuration allows you to set a minimum total coverage percentage for the run. This however allows you to add new code without tests as long as the total percentage does not fall under that value. Or you can have one file with 0% coverage as long as other files have large enough coverage to make up for this.

It would be good to be able to specify a `--cov-fail-any-under=MIN` configuration which would cause a failure if ANY file is under the coverage limit.

This would assist in projects moving towards full coverage.

**Comment by nedbat** [comment]
This would probably need to be a feature in coverage.py, similar to [per file coverage threshhold](https://github.com/nedbat/coveragepy/issues/691).

**Comment by bazzadp** [comment]
I stopped being lazy and just got my tests written 😉 So happy to close this.

Feel free to reopen if you think it would be useful for others to have this.
