### ISSUE TITLE
Is there any difference between running pytest --cov-report xml to coverage xml

### ISSUE THREAD

**Issue by arielman** [pytest-dev/pytest-cov#447]
Hi
I want to understand if there's any difference in the xml report between the below 2 methods:
1. `pytest --cov-report xml --cov=myproj tests/`
2. `coverage run -m pytest arg1` and then `coverage xml`

The only thing I saw its what written here:
[coverage-5.3](https://coverage.readthedocs.io/en/coverage-5.3/)
"Many people choose to use the pytest-cov plugin, but for most purposes, it is unnecessary."

**Comment by arielman** [comment]
Got the answer from conf page:
https://pytest-cov.readthedocs.io/en/latest/readme.html

This plugin produces coverage reports. Compared to just using coverage run this plugin does some extras:

Subprocess support: you can fork or run stuff in a subprocess and will get covered without any fuss.

Xdist support: you can use all of pytest-xdist’s features and still get coverage.

Consistent pytest behavior. If you run coverage run -m pytest you will have slightly different sys.path (CWD will be in it, unlike when running pytest).

**Comment by ionelmc** [comment]
@nedbat could we change that text in coverage about pytest-cov to at least hint about the subprocess/xdist stuff, currently it's so vague might as well not have it at all.
