### ISSUE TITLE
.coveragerc sometimes ignored

### ISSUE THREAD

**Issue by jaraco** [pytest-dev/pytest-cov#456]
# Summary

In jaraco/skeleton, I've configured my projects to [ignore .tox](https://github.com/jaraco/skeleton/blob/86efb884f805a9e1f64661ec758f3bd084fed515/.coveragerc#L2) for coverage. Despite this setting, I often see `.tox` in the coverage results. ([example](https://github.com/jaraco/cssutils/runs/2082642025?check_suite_focus=true#step:5:120)).

Not all projects are affected. Some show a report without tox (using the same config).

Note the tox lines do appear to implicate black or virtualenv (especially as 'click' is mentioned).

## Expected vs actual result

Expect `.tox` to be omitted as indicated.

# Reproducer

I've tried reproducing the issue in a [minimal repo](/jaraco/pytest-cov-456), and I can get the `.tox` results to appear if I run tests on a simple repo with only `pytest-cov` and `pytest-black` installed and enabled. But in that case, when I add the .coveragerc file, `.tox` disappears from the report, as expected. So there's something else about the projects that's causing the `.coveragerc` to be ignored. ~~Note also that omitting `pytest-black` causes the `.tox` lines to be omitted.~~

## Versions

See example above for one configuration (using latest version of everything), but it affects lots of versions and libraries.

## Config

See [jaraco/cssutils](/jaraco/cssutils) for one affected project.

Any advice on how I can troubleshoot further, to narrow the cause?

**Comment by ionelmc** [comment]
Try this:

```diff
diff --git a/.coveragerc b/.coveragerc
index 4582306..86bf291 100644
--- a/.coveragerc
+++ b/.coveragerc
@@ -1,5 +1,5 @@
 [run]
-omit = .tox/*
+omit = */.tox/*

 [report]
 show_missing = True
```

**Comment by ionelmc** [comment]
An alternative might be to set the source/source_pkgs to your package name, or src-layout your project and use src as the source.

**Comment by jaraco** [comment]
> Try [`omit = */.tox/*`]

Yes, that seems to work. Any idea why `.tox/*` works in some cases but not in others or why the issue only happens with pytest-cov and not `coverage pytest`?



> An alternative might be to set the source/source_pkgs to your package name, or src-layout your project and use src as the source (assuming editable installs).

I want to avoid `source/source_pkgs` because I'd like to avoid having to customize the config for each project. I similarly want to avoid using `src` because that puts a constraint on the viable source layouts for projects (and bring in the issues with those layouts).

I think the first option may be viable. I'll try it and see how it goes and report back if it's insufficient.

**Comment by smheidrich** [comment]
I just had the a similar issue and found out it was caused by lack of a trailing slash in the `--cov=my_pkg/` argument. For some reason, leaving that slash out made it disregard the `omit` option. But I wasn't trying to omit `.tox`. Rather, my package layout is like this:
```
project_root
+-my_pkg
| +-some_module.py
| +-tests
| | +-test_1.py
+-.coveragerc
```
and I'm trying to omit the `tests` directory by putting
```
[run]
omit = my_pkg/tests/*
```
in `.coveragerc`, then running `pytest` from `project_root` via `pytest --cov=my_pkg/ --cov-config=.coveragerc my_pkg/tests`. I thought the last argument specifying the pytest root directory might have been the problem, but it has no influence whatsoever. Only the `/` after the `--cov` argument fixes it.

Is this intended behavior?
