### ISSUE TITLE
Syntax error when setting up pytest-cov

### ISSUE THREAD

**Issue by martinlanton** [pytest-dev/pytest-cov#457]
# Summary
The latest version of pytest (here: https://pypi.org/project/pytest-cov/) mentions it supports python 3.5 and up
However, when running setup.py in a bare minimum environment, I get a syntax error.

## Expected vs actual result
Here's an example : https://github.com/martinlanton/tox_template_project/runs/2141979832?check_suite_focus=true
considering the simplicity of this package, I would expect it to run smoothly, however it seems to only run smoothly on python 3.6 and up.

What am I missing?

## Code
https://github.com/martinlanton/tox_template_project

Thanks :)

**Comment by ionelmc** [comment]
Looks like you have managed to install a pytest version that doesn't support 3.5. Try pytest 6.1.2.

**Comment by martinlanton** [comment]
Thanks for the quick answer!
Shouldn't by default pytest-cov pull the right dependencies based on the python version being used?

Also, any version of 6.1.2 >= pytest > 6 still gives me a syntax error, although a different one : https://github.com/martinlanton/tox_template_project/runs/2142178431?check_suite_focus=true
Even 5.4.3 gives me that new syntax error.

Any clue?

**Comment by ionelmc** [comment]
pytest-cov doesn't install pytest, it merely depends on it.

Looks like the problem is that you use `python setup.py develop` and that in turn uses easy_install's broken dependency resolver? Try `pip install -e .` instead.

Anyway, I'd just copy the CI boilerplate from another project or a cookiecutter template if I'm not invested into sorting out all these packaging problems, just saying.

**Comment by The-Compiler** [comment]
Let me just note that Python 3.5 [is EOL since last September](https://devguide.python.org/devcycle/#end-of-life-branches), so unless you have a good reason to support it, it's probably not worth the pain.

**Comment by martinlanton** [comment]
Thanks for all the answers. Yes, I think I'll just drop 3.5 as it doesn't really bring anything to me anyway.
