### ISSUE TITLE
move under pytest-dev organization

### ISSUE THREAD

**Issue by bubenkoff** [pytest-dev/pytest-cov#48]
please consider moving this nice plugin under pytest community-driven `pytest-dev` organization
for this just one single email to pytest-dev mailing list is enough
http://pytest.org/latest/contributing.html#id3

**Comment by schlamar** [comment]
will do after #28 is settled ;)

**Comment by schlamar** [comment]
https://mail.python.org/pipermail/pytest-dev/2015-July/003085.html

**Comment by fschulze** [comment]
You should be able to initiate an ownership transfer under "settings" of this project, then everything will be moved over and any forks will point to the new location as origin. That's the best way to move imho.

**Comment by nicoddemus** [comment]
@schlamar please transfer ownership to me so I can complete the move. :smile:

**Comment by schlamar** [comment]
Done. Please don't forget to add @ionelmc as contributor.

**Comment by nicoddemus** [comment]
Done. :smile:

Please let me know if you encounter any problems!
