### ISSUE TITLE
pytest-cov and pony-orm

### ISSUE THREAD

**Issue by tweigel-dev** [pytest-dev/pytest-cov#486]
# Summary
Hallo,
I have an issue regarding pytest-cov https://github.com/pytest-dev/pytest-cov and pony orm https://github.com/ponyorm/pony. 
If I try to cover the line of the **select** or **get** statements I get a weird message:
![image](https://user-images.githubusercontent.com/56434333/129187723-d12b6dcf-78a9-44ff-9fef-ad014f311863.png)

This also harms the coverage, because pytest thinks they are not covered.

Thanks for your help!

## Expected vs actual result
I my opinion this line should be fully covered.
# Reproducer

## Code

```python
from pony import orm
db = orm.Database()
class Hardware(db.Entity):
    hardware_id = orm.PrimaryKey(int, auto=True)
def func_to_t3st():
    hardware = orm.get(  h for h in Hardware if hardware_id == 2 )

def test_get_cov():
    orm.db_session():
        Hardware(hardware_id =2)
        orm.commit()
    func_to_t3st()


```

**Comment by nedbat** [comment]
This happens because PonyORM doesn't run the code you give it: it recompiles it and runs a different piece of code.  This is a long-standing issue with coverage.py: https://github.com/nedbat/coveragepy/issues/685
