### ISSUE TITLE
--cov-append complains of malformed .coverage files

### ISSUE THREAD

**Issue by sarahnlewis** [pytest-dev/pytest-cov#493]
I have coverage-5.5, pytest-6.2.5, and pytest-cov-2.12.1 installed.  I try running something like `pytest test_a --cov=.` and then `pytest test_b --cov=. --cov-append` and get a lot of errors like:
```
Coverage.py warning: Data file '/path/to/.coverage.xyz' doesn't seem to be a coverage data file: Couldn't use data file '/path/to/.coverage.xyz': no such table: coverage_schema
Coverage.py warning: Data file '/path/to/.coverage.abc' doesn't seem to be a coverage data file: cannot unpack non-iterable NoneType object
Coverage.py warning: Couldn't use data file '/path/to/.coverage.123': database disk image is malformed
```
How can I fix this? Roll back to earlier versions? If so, which versions? I found [this](https://github.com/nedbat/coveragepy/issues/408) faintly related issue where similar symptoms resulted from mismatched versions of `coverage`, but I only have one version of `coverage` installed and am executing everything in the same conda environment.
Many thanks.

**Comment by nedbat** [comment]
Can you find out more about what is in those files?  For example:
```
$ hexdump -C /path/to/.coverage.xyz | head -10
```

**Comment by sarahnlewis** [comment]
Thank you for the quick reply.

Many of the `.coverage` files are empty and these get the `no such table: coverage_schema` complaint.

The complaint about this one is `cannot unpack non-iterable NoneType object`:
```
$ hexdump -C ./.coverage....5926.908669 | head -10 
00000000  53 51 4c 69 74 65 20 66  6f 72 6d 61 74 20 33 00  |SQLite format 3.|
00000010  10 00 01 01 00 40 20 20  00 00 00 07 00 00 00 0d  |.....@  ........|
00000020  00 00 00 00 00 00 00 00  00 00 00 07 00 00 00 04  |................|
00000030  00 00 00 00 00 00 00 00  00 00 00 01 00 00 00 00  |................|
00000040  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
00000050  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 07  |................|
00000060  00 2e 53 60 0d 0f 56 00  0c 06 96 00 0f 5e 0d 58  |..S`..V......^.X|
00000070  0f 2d 0c a5 0d 2f 0b da  0c 76 09 93 0b a7 07 6a  |.-.../...v.....j|
00000080  09 6c 06 96 00 00 00 00  00 00 00 00 00 00 00 00  |.l..............|
00000090  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
```

The complaint about this one is `database disk image is malformed`:
```
$ hexdump -C .coverage....5668.021702 | head -10
00000000  53 51 4c 69 74 65 20 66  6f 72 6d 61 74 20 33 00  |SQLite format 3.|
00000010  10 00 01 01 00 40 20 20  00 00 00 01 00 00 00 02  |.....@  ........|
00000020  00 00 00 00 00 00 00 00  00 00 00 01 00 00 00 04  |................|
00000030  00 00 00 00 00 00 00 00  00 00 00 01 00 00 00 00  |................|
00000040  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
00000050  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 01  |................|
00000060  00 2e 53 60 0d 00 00 00  01 0f 5e 00 0f 5e 00 00  |..S`......^..^..|
00000070  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
*
00000f50  00 00 00 00 00 00 00 00  00 00 00 00 00 00 81 1f  |................|
```

**Comment by nedbat** [comment]
They are SQLite databases (as they should be).  Are there any other clues about strange occurrences? Are you running processes concurrently? Anything like that?

**Comment by sarahnlewis** [comment]
I believe multiprocessing is used in these tests, yes. Would you expect that to cause issues?

**Comment by nedbat** [comment]
I would not expect it to cause issues.  Something unusual is happening.  Can you give us a reproducible scenario, or link to your code?

**Comment by sarahnlewis** [comment]
The codebase I'm working with is not public. I will try to make a minimal repro that I can share. Thanks again.

**Comment by sarahnlewis** [comment]
I'll close this issue for now and file a new one if and when I create a minimal repro that I can share.
