### ISSUE TITLE
mock pymysql in function but effect in other module

### ISSUE THREAD

**Issue by vekee** [pytest-dev/pytest-cov#497]
# Summary
when i mock pymysql conn error with use [@pytest.fixture(autouse=True)]
it did successed  with pytest the py file
but other py file get failed with pytest-cov

with use pytest-cov,
at last, i find the mock_conn_error method is not only effected in one test class, sometime also effect in other module.
maybe this is a bug.

## mock_conn_error method is this
```python
@pytest.fixture(autouse=True)
def mock_conn_error():
    mock_conn = mock.MagicMock()
    mock_conn.side_effect = Exception
    pymysql.connect = mock_conn
```

## Versions
Python 3.8.0
pytest 6.2.4
pytest-cov 2.12.1

## Code for temp solution
mock pymysql conn error in every test method like this
```python
def test_somemethod():
    pass
    
   #mock
    mock_conn = mock.MagicMock()
    mock_conn.side_effect = Exception
    conn_bk = pymysql.connect
    pymysql.connect = mock_conn

    pass

    #release the mock
    pymysql.connect = conn_bk
```

**Comment by graingert** [comment]
You'll need to use the context manager interface:

```python
with mock.patch.object(pymysql, "connect", side_effect=Exception) as mock_connect:
    yield mock_connect
```

This isn't related to pytest-cov however

**Comment by vekee** [comment]
> You'll need to use the context manager interface:
> 
> ```python
> with mock.patch.object(pymysql, "connect", side_effect=Exception) as mock_connect:
>     yield mock_connect
> ```
> 
> This isn't related to pytest-cov however

Thank You brother!

context manager resolve the problem in 「@pytest.fixture(autouse=True)」 method like what in your answer.
'''
@pytest.fixture(autouse=True)
def mock_conn_error():
     with mock.patch.object(pymysql, "connect", side_effect=Exception) as mock_connect:
         yield mock_connect
'''
