### ISSUE TITLE
Are packages imported prior to test run excluded from coverage report?

### ISSUE THREAD

**Issue by LachlanMarnham** [pytest-dev/pytest-cov#519]
# Summary
I am trying to use `pytest-cov`, but not in conjunction with the `pytest` CLI. Instead, I am calling `pytest` from inside my code, and I am getting incorrect coverage results. I am wondering if packages imported before `pytest` is called are ignored by the  `pytest-cov` report.

## Expected vs actual result
If, on the command line, I execute:

```
$ pytest --cov=my_package
```

the reported total coverage is 93.72% (this is correct). If I run the following file:

```python
import pytest

pytest.main(['--cov', 'my_package'])
```

I again get a coverage of 93.72%. However, if I modify this file slightly:

```python
import pytest
from my_package import foo, bar

pytest.main(['--cov', 'my_package'])
```

the coverage report is incorrect.

## Versions

`pytest-cov==3.0.0`
`pytest==6.2.5`

## Code

Note: my code will be harder to parse than the minimal working example above, but I will provide it on request if required.

# What has been tried to solve the problem

This is really just a question, it may be expected behaviour and not a problem. But if there is a way to avoid it and get accurate coverage that would be appreciated!

**Comment by LachlanMarnham** [comment]
After further investigation, it seems this is a feature/bug in `coverage.py`, not `pytest-cov`. For anybody who has the same question, I've opened an issue against `coverage.py` here: https://github.com/nedbat/coveragepy/issues/1311

**Comment by ionelmc** [comment]
Regardless, you might want to take a look at https://pytest-cov.readthedocs.io/en/latest/plugins.html
