### ISSUE TITLE
Coverage report for a subset of packages

### ISSUE THREAD

**Issue by ryotatomioka** [pytest-dev/pytest-cov#528]
# Summary
I have a mono repo that contains multiple packages and projects. A project depends on a subset of packages. Therefore, I would like to produce a coverage report for each project (that is, disregarding packages that the project doesn't depend on).

The mono repo looks like this:
<img width="173" alt="image" src="https://user-images.githubusercontent.com/19404559/159115751-bd3799f4-688e-430e-85d2-fad196d1b56d.png">

For example, I have a project that depends on `packageA` and `packageB`. I tried
```
cd <REPO_ROOT>
PYTHONPATH=packages pytest --cov=packages/packageA --cov=packages/packageB --cov-report=xml pack
ages/packageA packages/packageB
```
and also
```
cd <REPO_ROOT>/packages
PYTHONPATH=. pytest PYTHONPATH=. pytest --cov=packageA --cov=packageB --cov-report=xml packageA packageB
```

In both cases, I get `coverage.xml` that looks like this
<img width="513" alt="image" src="https://user-images.githubusercontent.com/19404559/159115969-acde3efd-0261-447f-8618-91c913daaae6.png">

As you can see, the contents of `packages/packageA` and `packages/packageB` are mixed in one package with name `.`.

## Expected vs actual result

If I run `coverage` directly as follows:
```
cd <REPO_ROOT>/packages
PYTHONPATH=. coverage run --source=packageA,packageB -m pytest packageA packageB
coverage xml
```

I get `coverage.xml` that looks like this
<img width="545" alt="image" src="https://user-images.githubusercontent.com/19404559/159116108-8c7ad0d6-0b25-4cc5-93fa-446b54330ae1.png">

Namely, the `<sources>` section contains only one source `<REPO_ROOT>/packages` and the `<packages>` section has `packageA`, `packageA.tests`, `packageB`, etc separated.

I have a hunch about this difference in the behavior: `pytest-cov` uses essentially the same `CoverageConfig` for both running the tests and producing the XML report, whereas if I invoke `coverage` as above, `--source` option is only fed into `coverage run` and not into `coverage xml`.

I don't know if this is an intended behavior of `coverage` but since there is no way to provide `--source` option to `coverage xml`, it seems like it. From `pytest-cov`, the same behavior can be achieved if we (temporarily) clean `self.cov.config.source` before this line
https://github.com/pytest-dev/pytest-cov/blob/4cfbe1426f681770360294718ca9e2fe0bb9c229/src/pytest_cov/engine.py#L196

# Reproducer
[packages.tar.gz](https://github.com/pytest-dev/pytest-cov/files/8308925/packages.tar.gz)

## Versions
pytest==6.2.5
pytest-cov==3.0.0
coverage==6.0.2

**Comment by nedbat** [comment]
If it works to run coverage directly, why isn't that your solution?

**Comment by ryotatomioka** [comment]
OK I thought `pytest-cov` was meant to be consistent with the behavior of `coverage` but I must have misunderstood.
