### ISSUE TITLE
Force coverage to run even when `--cov` is not set.

### ISSUE THREAD

**Issue by abrisco** [pytest-dev/pytest-cov#542]
# Summary

I would like to collect coverage for an explicit set of source files. Outside of pytest-cov, I can make a `coveragerc` that uses [include](https://coverage.readthedocs.io/en/6.4.1/config.html#run-include) to specify what I want. However, with `pytest-cov` I'm not able to use my `coveragerc` file due to the fact that coverage is not run unless `--cov` is set at least once. If [this block in plugin.py](https://github.com/pytest-dev/pytest-cov/blob/v3.0.0/src/pytest_cov/plugin.py#L148-L150) were to allow coverage to run even if `cov_source` is empty, I can use my `coveragerc` file.

## why is the feature needed?

I encountered this while trying to run pytest and collect coverage using [Bazel](https://bazel.build/). Bazel's interaction with Python is quite a bit different than most traditional python build systems in that it generally lacks the understanding of python modules. In the very large python code bases I've worked with using Bazel, tracking "packages" as collections of files leads to more accurate results, is more performant, and is less taxing for code maintainers.

## what problem does it solve?

Users would be able to use `pytest-cov` without either patching it or rewriting their own plugin.

## how it is better compared to past solutions to the problem?

This issue seems fairly unique. The only option I've been able to find is to either not use pytest-cov or to patch it. Adding some kind flag to force coverage to run regardless of `cov_source` would be very helpful.

**Comment by nedbat** [comment]
Why not just use `coverage run` directly instead of pytest-cov?

**Comment by abrisco** [comment]
> Why not just use `coverage run` directly instead of pytest-cov?

It integrates with pytest-dist. Something I was not able to easily do with running coverage directly.

**Comment by abrisco** [comment]
@ionelmc friendly ping, does something like this sound reasonable to support?

**Comment by ionelmc** [comment]
Having coverage always on? Absolutely not. Most users do not desire something like that.

**Comment by ionelmc** [comment]
Either way it's not clear to me what you're trying to solve (iow: what is the actual problem in you project).

Have you read https://pytest-cov.readthedocs.io/en/latest/plugins.html ?

**Comment by abrisco** [comment]
> Having coverage always on? Absolutely not. Most users do not desire something like that.

No, a flag to force coverage to turn on in cases where a coveragerc has all the include/exclude information. I have read the docs and it doesn't cover this use case.

**Comment by nedbat** [comment]
If pytest-cov is misbehaving for you, try using coverage.py without it:
```
coverage run -m pytest <pytest args>
```

**Comment by abrisco** [comment]
> If pytest-cov is misbehaving for you, try using coverage.py without it:
> 
> ```
> coverage run -m pytest <pytest args>
> ```

I had originally tried to run coverage directly but it misbehaved with [pytest-xdist](https://pypi.org/project/pytest-xdist/).

**Comment by abrisco** [comment]
I revisited my need for this feature and was able to get the plugin to behave as I had wanted. I'm not sure what I'd done before to cause it to not find my coverage. My hypothesis is I was passing `--cov=` vs `--cov` but have not had any bandwidth to go back and confirm. Today I can generate coverage config files with absolute paths to the files I want coverage for and the plugin works with and without `pytest-xdist`. Thanks everyone for taking a look and suggesting solutions. Much appreciated!
