### ISSUE TITLE
Why can't coverage the data in the "if __name__ == "__main__":"

### ISSUE THREAD

**Issue by alittlesir** [pytest-dev/pytest-cov#552]
test.py
```
if __name__ == "__main__":
    print("hello world!")
```

run：`pytest --cov=./ test.py`

output：
```
----------- coverage: platform linux, python 3.9.9-final-0 -----------
Name      Stmts   Miss  Cover
-----------------------------
test.py       2      1    50%
-----------------------------
TOTAL         2      1    50%

```
The normal coverage rate should be 100%.  why 50%.

![image](https://user-images.githubusercontent.com/67537842/187212558-f260487c-ef5c-4a1c-aea0-440d52df41dc.png)

**Comment by alittlesir** [comment]
nobody respond? it is a bug?

**Comment by Segelzwerg** [comment]
I think we experienced the same thing. The coverage was lost from 3.0.0 to 4.0.0.

https://github.com/Whist-Team/Whist-Core/pull/247
https://github.com/Whist-Team/Whist-Server/pull/359

**Comment by ionelmc** [comment]
@Segelzwerg you're using multiprocessing in your test suite, support for it was removed in pytest-cov 4. See the changelog for migration path: https://pytest-cov.readthedocs.io/en/latest/changelog.html

**Comment by Segelzwerg** [comment]
> @Segelzwerg you're using multiprocessing in your test suite, support for it was removed in pytest-cov 4. See the changelog for migration path: https://pytest-cov.readthedocs.io/en/latest/changelog.html

@ionelmc thanks for the advice. I didn't realize it. Will investigate now!
