### ISSUE TITLE
Add support for "--concurrency" option

### ISSUE THREAD

**Issue by lukasab** [pytest-dev/pytest-cov#591]
# Summary

I know it's possible to use the coverage config file `.coveragrc` for this but would be great if I could use it direcly with `pytest` so no extra file is required. I can probrably develop this feature but wanted to know if it's something you guys also think is valuable.

* why is the feature needed?
Specify the concurrency option (Needed for projects that don't use the default concurrency option (thread))
* what problem does it solve?
No need to create a `.coveragrc` file 
* how it is better compared to past solutions to the problem?
Might be my personal opinion, but I already have so many files in my project and I don't want to introduce a new one just for a small change

**Comment by nedbat** [comment]
You can configure coverage.py in .coveragerc, or setup.cfg, or tox.ini, or pyproject.toml.  If you have any of those files, you can add this setting without creating a new file.

**Comment by lukasab** [comment]
Oh great, this is for sure a better solution, thx.
[Here](https://coverage.readthedocs.io/en/7.2.2/config.html#configuration-reference) is the docs about it if anybody comes across this issue.

And how it would look like in `pyproject.toml`
```
[tool.coverage.run]
concurrency = greenlet,thread
```
