### ISSUE TITLE
cov-fail-under should round before comparing

### ISSUE THREAD

**Issue by bthorben** [pytest-dev/pytest-cov#601]
# Summary

Our tests fail with a message similar to
`FAIL Required test coverage of 54.18% not reached. Total coverage: 54.18%`
as you can see from this message, it actually looks like the coverage is reached. It should only fail if the coverage is less, not if it's equal. 

My guess is that these numbers are rounded and are actually not equal. 

## Expected vs actual result

Actual: Fails when coverage is qual expected value
Expected: Only fail if it is less

# Reproducer

## Versions

pytest-cov==4.1.0
pytest==7.3.2

**Comment by nedbat** [comment]
Can you show us the exact actual message you are seeing?

**Comment by bthorben** [comment]
```
FAIL Required test coverage of 54.18% not reached. Total coverage: 54.18%
```
is the actual message, nothing else. Maybe I misunderstood?!

**Comment by nedbat** [comment]
No, you're good, my mistake.
