### ISSUE TITLE
cov-config file argument ignored when tox.ini exists

### ISSUE THREAD

**Issue by schivmeister** [pytest-dev/pytest-cov#615]
# Summary

When supplying `--cov-config=$file` (where `$file` is e.g. `setup.cfg`) in the presence of a `tox.ini` with a `[pytest]` section, pytest/coverage will continue to pick up configuration from `tox.ini`.

## Expected vs actual result

**Expected:** Configuration from `$file` is picked up because an override argument has been supplied.
**Actual:** The `--cov-config` argument is being ignored when there is a valid `tox.ini` with a `[pytest]` section.

# Reproducer

## Versions

Windows 11 Pro 22H2
Python 3.8.18 (Anaconda)

**pip list**
```
pytest                        7.4.2
pytest-cov                    4.1.0
```

## Config

**tox.ini** (w/ empty `pytest` section)
```
[tox]
skipsdist = true
envlist = py38

[testenv]
passenv = *
deps =
    -rrequirements.txt
commands =
    python -m pytest

[pytest]
```

**setup.cfg** (w/ additional pytest-cov config/opts)
```
[tool:pytest]
addopts =
    --cov-report=xml
    -r a
    -q
    -v
    --gherkin-terminal-reporter
    --log-level=DEBUG
```

## Code

Above config files are the MWE. The test output will not contain the XML file from the configuration in `$file` (e.g. `setup.cfg`) because the `tox.ini` file is prioritized, which has an empty `[pytest]` section.

**Comment by javiersrf** [comment]
I got the same problem but using `--cov-config=setup.cfg`. Still using the values of `.coveragerc` :disappointed:

**Comment by ionelmc** [comment]
I think you have confused the pytest config file with the coverage config file (that configures coverage, not pytest). The `--cov-config` cli argument sets the coverage config file.
