### ISSUE TITLE
coverage precision option

### ISSUE THREAD

**Issue by zx80** [pytest-dev/pytest-cov#655]
Coverage supports the `--precision` option which is convenient to adjust reported and expected subpercent coverage, however `pytest-cov` seems not to offer a corresponding `--cov-precision` option.

**Comment by ionelmc** [comment]
Do you really need a cli option for this? You can set it in your coverage config file: https://coverage.readthedocs.io/en/7.6.1/config.html#report-precision

**Comment by zx80** [comment]
Thanks for the feedback. Sure, it is possible.

Philosophically, I try to avoid having files which change the behavior of commands if I can, in order to have a functional command behavior without such hidden side effects.

Option `--show-missing` has its `--cov-show-missing` counterpart, why _not_ `--precision` which is somehow related to that?

**Comment by ionelmc** [comment]
Well ok. Would you be interested in making a pr?

**Comment by zx80** [comment]
Possibly. I will have a look.

**Comment by zx80** [comment]
:+1:
