### ISSUE TITLE
Its getting extra statement somehow.

### ISSUE THREAD

**Issue by mohd-minhal** [pytest-dev/pytest-cov#659]
As the title, its basically giving 1 missing out of nowhere and not even marking.

and there are multiple files like this 
![Screenshot 2024-09-23 203825](https://github.com/user-attachments/assets/d375fc00-2bf0-4067-92a1-93aedc5180f2)
as you could see for some missing it didn't even marked missing.

example case
![Screenshot 2024-09-23 202339](https://github.com/user-attachments/assets/09def657-5241-4190-9719-0cdf8cc0fd90)

My two cents :
Is it the case where some portion of statement not getting test covered and its couldn't marked it because some portion is already covered.( I know it sounds dumb)

Well I wouldn't have reported an issue if it was just adding extra statement, and increases the coverage percentage but damn it's decreasing it.

**Comment by mohd-minhal** [comment]
Also its this https://github.com/mohd-minhal/fyle-interview-intern-backend, maybe it will help.

**Comment by nedbat** [comment]
I notice you are using coverage.py 5.5.  That's quite old, can you try using the latest version of coverage?

**Comment by mohd-minhal** [comment]
Thanks man it solved it, Now I feel more dumber.
