### ISSUE TITLE
Update links

### ISSUE THREAD

**Issue by schlamar** [pytest-dev/pytest-cov#73]
Point everything to https://github.com/pytest-dev/pytest-cov

Not important though, as redirection works.

**Comment by nicoddemus** [comment]
I was about to write a PR for that, but remembered that there's more work involved in this:

- [ ] Enable travis and appveyor integration in the new location (might be working already, not sure)
- [ ] Update readthedocs
- [ ] coveralls
- [ ] Update PyPI README

:sweat_smile:

**Comment by ionelmc** [comment]
I've added the project in appveyor (for some reason it's under my nickname https://ci.appveyor.com/project/ionelmc/pytest-cov but [builds from the right repo](https://ci.appveyor.com/project/ionelmc/pytest-cov/build/master-1/job/vn9tvwg8dsl9m8vx#L20)!?)

Travis was already on.

**Comment by nicoddemus** [comment]
GitHub also redirects git requests, so `git clone` from the old location still works for example.

**Comment by ionelmc** [comment]
@nicoddemus Seems there's https://ci.appveyor.com/project/pytestbot/pytest but I can't seem to add the project under that account (even if I can log in with it in appveyor). What's going on here? :grin:

**Comment by nicoddemus** [comment]
That's the account we created to migrate the issues, sorry! I sent that account password to "contact @ ionelmc.ro". It is meant to be shared between all pytest-dev contributors for registration in services that don't support a GH organization directly.

**Comment by ionelmc** [comment]
@schlamar it seems you're the only person who can edit https://readthedocs.org/projects/pytest-cov/

**Comment by schlamar** [comment]
Done.

**Comment by ionelmc** [comment]
Links should be fine now.
