### ISSUE TITLE
init_cov_core.pth references

### ISSUE THREAD

**Issue by opoplawski** [pytest-dev/pytest-cov#74]
PKG-INFO and README.rst still refer to init_cov_core.pth

**Comment by ionelmc** [comment]
By `PKG-INFO` you mean the description shown on the PyPI page right?

**Comment by opoplawski** [comment]
I mean the PKG-INFO file inside the PyPI tarball.  Which may be displayed on the PyPI page as well, but that's where I noticed it.

**Comment by ionelmc** [comment]
The PyPI page is updated now. The dists will get updated on the next release.

**Comment by ionelmc** [comment]
Also see #73.
