### ISSUE TITLE
Where is the cov-core 1.15.0

### ISSUE THREAD

**Issue by ju2wheels** [pytest-dev/pytest-cov#75]
Hi im doing custom packaging for stuff and was wondering where the source for cov-core 1.15.0 which can be found in pypi is?

The upstream cov-core repo only has up to 1.14.0 and some of the forks of cov-core are pointing to this repo as its continued development but im not finding that particular version anywhere.

[edit] I know we can just grab the pypi tarball and use that but I was just curious why it wasnt in the official upstream repo?

**Comment by ionelmc** [comment]
We could possibly figure out what happened but is it worth finding out? What's the issue with the forks? Are there some fixes that we should integrate?

**Comment by ju2wheels** [comment]
> We could possibly figure out what happened but is it worth finding out?

I guess thats relative.

> What's the issue with the forks?

As a packager I'd rather not use them. The official repo was http://github.com/schlamar/cov-core since thats whats linked to from PyPi. However PyPi has the latest cov-core package at 1.15.0 and that repo has only up to 1.14.0 . Looking at the forks there is a branch with 1.15.0 but I havent checked if this is the same as what is on PyPi or its some random person's one off and they are calling it 1.15.0 .

To me, schlamar/cov-core is the "trusted" source but its not up to date with PyPi. It only matters to me as im doing automated package build stuff and id rather be able to submodule cov-core than maintaining the tarball of 1.15.0 on my end even if it is EOL. Since its still widely used it would help for the original source to have 1.15.0 instead of PyPi being the only official source of it.

I asked this question here instead of on schlamar/cov-core since one of the forks said this was the continuation of cov-core, not sure what the current relation there is now.

> Are there some fixes that we should integrate?

Dont know, I havent compared the last official 1.14.0 to 1.15.0 thats on Pypi.

**Comment by ionelmc** [comment]
pytest-cov doesn't use cov-core anymore (it has been merged into pytest-cov to simplify code and release management).

Are you using other package that depend on cov-core?

Is there any particular reason you need to use the older pytest-cov (<2.0)?

**Comment by schlamar** [comment]
There is something weird going on... Looks like some of the commits are
gone. I had this problem before, then GitHub told me I did a force push.
But I wouldn't do an accidental force push to master twice. So I'll
investigate.

However, as cov-core has been merged into pytest-cov the commits should be
restorable.

Here is the 1.15 release commit:
https://github.com/pytest-dev/pytest-cov/commit/791b1f6890456ee9e3beec33c89a7c573a382b7b
I guess I forgot to push the tag.
Am 31.07.2015 23:19 schrieb "Ionel Cristian Mărieș" <
notifications@github.com>:

**Comment by ju2wheels** [comment]
> Are you using other package that depend on cov-core?

Yes the other packages im building still depend on cov-core.

> Here is the 1.15 release commit:
https://github.com/pytest-dev/pytest-cov/commit/791b1f6890456ee9e3beec33c89a7c573a382b7b
I guess I forgot to push the tag.

Awesome, that works for me, ty. I can pin to that so thats good enough for what I was trying to do with submodules and pinning to an official repo.
