### ISSUE TITLE
AppVeyor not testing anymore

### ISSUE THREAD

**Issue by schlamar** [pytest-dev/pytest-cov#81]
cc @ionelmc

**Comment by schlamar** [comment]
cc @nicoddemus

**Comment by schlamar** [comment]
The webhook is broken. Not sure what happened but I guess we should re-add the project on AppVeyor to update the webhook. Unfortunately, I have no permission to do that.

**Comment by ionelmc** [comment]
I've manually added the webhook, lets see if https://github.com/pytest-dev/pytest-cov/pull/82 works

**Comment by schlamar** [comment]
Thanks
