### ISSUE TITLE
Branch coverage please

### ISSUE THREAD

**Issue by dimaqq** [pytest-dev/pytest-cov#85]
Please allow turning on branch coverage.
IMO it should be the default too.

**Comment by ionelmc** [comment]
You can enable branch coverage via `.coveragerc`. Do you really need a command line argument?

**Comment by alexamici** [comment]
You may enable branch coverage in your setup.cfg file as well by adding:
```
[coverage:run]
branch = True
```

**Comment by JonasOlson** [comment]
It looks like it [used to](https://pypi.python.org/pypi/pytest-cov/0.6) be possible to turn on branch coverage easily with `--cov-branch`, just like you still use options like `--cov-report` or `--cov-fail-under`. Can we have that back?

**Comment by ionelmc** [comment]
@JonasOlson yes but why? what's wrong with putting it in `.coveragerc`?

**Comment by Juanlu001** [comment]
> @JonasOlson yes but why? what's wrong with putting it in .coveragerc?

Nothing wrong with it, but I agree with @JonasOlson and others that this option is too common to not have it available on the command line.

**Comment by JonasOlson** [comment]
@ionelmc: The command line argument is useful for the same reason any other command line argument is. Being able to run a command should preferably not have to include first creating, or rewriting, a file describing that command. You might not even have write access, or you might be running commands with different options every time, perhaps simultaneously. A configuration file might make sense when you want to use the same complex options over and over again, but I don't think it should replace command line options.

**Comment by sashgorokhov** [comment]
Currently I have a two-line `.coveragerc` with 
```
[run]
branch = True
```
in my several projects and this is boring. I really would like to have a command-line argument for this.
