### ISSUE TITLE
Incompatible with coverage 4.0?

### ISSUE THREAD

**Issue by reywood** [pytest-dev/pytest-cov#93]
I just ran a `pip upgrade` on my project which upgraded the coverage package from 3.7.1 to 4.0.0. When I ran `py.test --cov`, the output indicated that my test coverage had plummeted from 70% to 30%. A warning was also printed out: `Coverage.py warning: Trace function changed, measurement is likely wrong: None`. Downgrading the coverage package back to 3.7.1 fixes the problem. Has anyone else run into this?

**Comment by The-Compiler** [comment]
FWIW, it works fine for my project. Is your project available somewhere, or do you have an example where this happens? Do you use `sys.settrace` in your project?

**Comment by ionelmc** [comment]
Also, does any of your libraries use `sys.settrace`? Might be some bad interation.

Try grepping your site-packages for `sys.settrace`.

**Comment by reywood** [comment]
I was able to figure out what was causing the warning. I had a class that was doing something not too smart. This is a greatly simplified version of the class.

```python
class MyClass(object):
    def __getattr__(self, name):
        if not hasattr(self, 'some_field'):
            raise AttributeError()
```

`MyClass` was meant to be subclassed, with subclasses defining the `some_field` attribute. I had a test that asserted that `AttributeError` is raised if `some_field` is not defined. I'm not sure why that doesn't cause infinite recursion, instead of causing that warning message, or why it works in 3.7.1 but not 4.0.0, but there you have it.

Apologies for the distraction.
