### ISSUE TITLE
Allow to specify Coverage XML output file

### ISSUE THREAD

**Issue by blueyed** [pytest-dev/pytest-cov#97]
I have not looked to deep, but only found this:

```
src/pytest_cov/engine.py
108: stream.write('Coverage XML written to file %s\n' % self.cov.config.xml_output)
```

Therefore it appears that the output path can only be configured through the `.coveragerc` file.

It would be nice if this could be passed in through an option to pytest-cov, e.g. `--cov-xml-output=coverage2.xml`.

**Comment by ionelmc** [comment]
That would overlap a bit with the `--cov-report=xml` option. Maybe `--cov-report=xml` should be implied if you use `--cov-xml-output=coverage2.xml`. 

What if we'd be allowed to use `--cov-report=xml:coverage2.xml`?

**Comment by The-Compiler** [comment]
> What if we'd be allowed to use `--cov-report=xml:coverage2.xml` (or similar)?

That sounds good, and something similar could also be done for `--cov-report=html:htmlcov2`

**Comment by blueyed** [comment]
> `--cov-report=xml:coverage2.xml`

:+1:

**Comment by ionelmc** [comment]
Actually this was fixed in https://github.com/pytest-dev/pytest-cov/pull/113.
