### ISSUE TITLE
No coverage data is collected for installed package when py.test is run in the project's root directory

### ISSUE THREAD

**Issue by jck** [pytest-dev/pytest-cov#98]
If I have a package(and pytest-cov) installed in a virtualenv, and I run pytest-cov from the project's root directory(which has the package folder), then no coverage data is collected.

**Comment by ionelmc** [comment]
Hey, I need more details to figure out what's going on:

* how do you run pytest
* pytest configuration (`tox.ini`/`setup.cfg`/`pytest.ini`)
* coverage configuration (`.coveragerc`)

**Comment by jck** [comment]
Steps to reproduce the bug:

* clone https://github.com/jck/mylib
* create fresh virtualenv
* pip install pytest-cov
* pip install .
* py.test --cov mylib

```
~/t/mylib git:master ❮❮❮ py.test --cov mylib                                                                                                                                                     v:7573fdbc6e567b2 
=============================================================================================== test session starts ================================================================================================
platform linux -- Python 3.5.0, pytest-2.8.2, py-1.4.30, pluggy-0.3.1
rootdir: /home/jck/tmp/mylib, inifile: 
plugins: cov-2.2.0
collected 1 items 

tests/test_mylib.py .Coverage.py warning: No data was collected.

---------------------------------------------------------------------------------- coverage: platform linux, python 3.5.0-final-0 ----------------------------------------------------------------------------------
Name                Stmts   Miss  Cover
---------------------------------------
mylib/__init__.py       7      7     0%

============================================================================================= 1 passed in 0.01 seconds =============================================================================================
~/t/mylib git:master ❯❯❯ cd tests                                                                                                                                                              ◼ v:7573fdbc6e567b2 
~/t/m/tests git:master ❮❮❮ py.test --cov mylib                                                                                                                                                 ◼ v:7573fdbc6e567b2 
=============================================================================================== test session starts ================================================================================================
platform linux -- Python 3.5.0, pytest-2.8.2, py-1.4.30, pluggy-0.3.1
rootdir: /home/jck/tmp/mylib, inifile: 
plugins: cov-2.2.0
collected 1 items 

test_mylib.py .
---------------------------------------------------------------------------------- coverage: platform linux, python 3.5.0-final-0 ----------------------------------------------------------------------------------
Name                                                                                               Stmts   Miss  Cover
----------------------------------------------------------------------------------------------------------------------
/home/jck/.local/share/virtualenvs/7573fdbc6e567b2/lib/python3.5/site-packages/mylib/__init__.py       7      2    71%

============================================================================================= 1 passed in 0.01 seconds =============================================================================================
```

**Comment by ionelmc** [comment]
Seems to be working as expected for me:
```
============================================================================================================ test session starts ============================================================================================================
platform linux -- Python 3.5.0, pytest-2.8.2, py-1.4.30, pluggy-0.3.1
rootdir: /home/ionel/sandbox/mylib, inifile:
plugins: cov-2.2.0
collected 1 items

tests/test_mylib.py .
---------------------------------------------------------------------------------------------- coverage: platform linux, python 3.5.0-final-0 -----------------------------------------------------------------------------------------------
Name                                                                  Stmts   Miss  Cover
-----------------------------------------------------------------------------------------
.ve/lib/python3.5/codecs.py                                             398    389     2%
.ve/lib/python3.5/encodings/__init__.py                                  65     54    17%
.ve/lib/python3.5/site-packages/_pytest/_argcomplete.py                  35     34     3%
.ve/lib/python3.5/site-packages/_pytest/assertion/__init__.py            81     45    44%
.ve/lib/python3.5/site-packages/_pytest/assertion/newinterpret.py       268    200    25%
.ve/lib/python3.5/site-packages/_pytest/assertion/reinterpret.py         36     13    64%
.ve/lib/python3.5/site-packages/_pytest/assertion/rewrite.py            523    373    29%
.ve/lib/python3.5/site-packages/_pytest/assertion/util.py               222    202     9%
.ve/lib/python3.5/site-packages/_pytest/cacheprovider.py                137    103    25%
.ve/lib/python3.5/site-packages/_pytest/capture.py                      308    250    19%
.ve/lib/python3.5/site-packages/_pytest/config.py                       759    632    17%
.ve/lib/python3.5/site-packages/_pytest/doctest.py                      146    142     3%
.ve/lib/python3.5/site-packages/_pytest/genscript.py                     81     78     4%
.ve/lib/python3.5/site-packages/_pytest/helpconfig.py                    95     87     8%
.ve/lib/python3.5/site-packages/_pytest/junitxml.py                     178    176     1%
.ve/lib/python3.5/site-packages/_pytest/main.py                         511    292    43%
.ve/lib/python3.5/site-packages/_pytest/mark.py                         160    152     5%
.ve/lib/python3.5/site-packages/_pytest/monkeypatch.py                  115    103    10%
.ve/lib/python3.5/site-packages/_pytest/nose.py                          42     28    33%
.ve/lib/python3.5/site-packages/_pytest/pastebin.py                      58     57     2%
.ve/lib/python3.5/site-packages/_pytest/pdb.py                           78     71     9%
.ve/lib/python3.5/site-packages/_pytest/python.py                      1390   1073    23%
.ve/lib/python3.5/site-packages/_pytest/resultlog.py                     84     82     2%
.ve/lib/python3.5/site-packages/_pytest/runner.py                       333    223    33%
.ve/lib/python3.5/site-packages/_pytest/skipping.py                     212    182    14%
.ve/lib/python3.5/site-packages/_pytest/terminal.py                     439    325    26%
.ve/lib/python3.5/site-packages/_pytest/tmpdir.py                        62     55    11%
.ve/lib/python3.5/site-packages/_pytest/unittest.py                     144    137     5%
.ve/lib/python3.5/site-packages/_pytest/vendored_packages/pluggy.py     413    277    33%
.ve/lib/python3.5/site-packages/mylib/__init__.py                         7      2    71%
.ve/lib/python3.5/site-packages/pkg_resources/__init__.py              1607   1604     1%
.ve/lib/python3.5/site-packages/py/_apipkg.py                           138    109    21%
.ve/lib/python3.5/site-packages/py/_builtin.py                          188    177     6%
.ve/lib/python3.5/site-packages/py/_code/code.py                        523    498     5%
.ve/lib/python3.5/site-packages/py/_code/source.py                      285    165    42%
.ve/lib/python3.5/site-packages/py/_error.py                             50     45    10%
.ve/lib/python3.5/site-packages/py/_io/saferepr.py                       49     28    43%
.ve/lib/python3.5/site-packages/py/_io/terminalwriter.py                234    151    35%
.ve/lib/python3.5/site-packages/py/_path/common.py                      244    153    37%
.ve/lib/python3.5/site-packages/py/_path/local.py                       628    490    22%
.ve/lib/python3.5/site-packages/py/_std.py                               11      5    55%
.ve/lib/python3.5/site-packages/py/_xmlgen.py                           170    168     1%
.ve/lib/python3.5/site-packages/pytest_cov/engine.py                    156    145     7%
.ve/lib/python3.5/site-packages/pytest_cov/plugin.py                    101     90    11%
tests/test_mylib.py                                                       4      0   100%
-----------------------------------------------------------------------------------------
TOTAL                                                                 11768   9665    18%

========================================================================================================= 1 passed in 1.16 seconds ==========================================================================================================
```

**Comment by ionelmc** [comment]
Note the `.ve/lib/python3.5/site-packages/mylib/__init__.py                         7      2    71%`

I think what you need here is a path mapping in `.coveragerc`

**Comment by ionelmc** [comment]
To be honest I have never figured out how to get that damn mapping to work (https://coverage.readthedocs.org/en/latest/config.html#paths) so I always have two envs, one for normal runs and one for coverage runs (where something alone the lines of `pip install -e .` happens - editable installs). See [this](http://blog.ionelmc.ro/2014/05/25/python-packaging/).

**Comment by jck** [comment]
What was your PWD and command from the output you posted?

**Comment by ionelmc** [comment]
I was in the root of the repo (/home/ionel/sandbox/mylib).
​
​​

**Comment by ionelmc** [comment]
You also appear to have the expected result:
```
~/t/m/tests git:master ❮❮❮ py.test --cov mylib                                                                                                                                                 ◼ v:7573fdbc6e567b2 
=============================================================================================== test session starts ================================================================================================
platform linux -- Python 3.5.0, pytest-2.8.2, py-1.4.30, pluggy-0.3.1
rootdir: /home/jck/tmp/mylib, inifile: 
plugins: cov-2.2.0
collected 1 items 

test_mylib.py .
---------------------------------------------------------------------------------- coverage: platform linux, python 3.5.0-final-0 ----------------------------------------------------------------------------------
Name                                                                                               Stmts   Miss  Cover
----------------------------------------------------------------------------------------------------------------------
/home/jck/.local/share/virtualenvs/7573fdbc6e567b2/lib/python3.5/site-packages/mylib/__init__.py       7      2    71%

============================================================================================= 1 passed in 0.01 seconds =============================================================================================

```

**Comment by ionelmc** [comment]
I think this can be closed. I don't think there's a way to solve this in pytest-cov. Maybe report issue with paths mapping at https://bitbucket.org/ned/coveragepy/ ?

**Comment by jck** [comment]
I have the expected result when my pwd is the tests subdirectory.

When I run from the project root, I get nothing.

**Comment by ionelmc** [comment]
Ok, and if you run just `py.test --cov` (no package name) in the root?

**Comment by jck** [comment]
aah, I get the same results as you in that case.

**Comment by ionelmc** [comment]
Ok, so not a `pytest-cov` issue yes? :)

**Comment by Natim** [comment]
When having the issue with tox, I turned `usedevelop = True` and it fixed the issue.

**Comment by normanpilusa** [comment]
I had the same problem. I had a wrong folder name here:
COV = coverage.coverage(branch=True, include='**_my_Folder/_**')

**Comment by Midnighter** [comment]
Another option with tox is to set the base folder in `tox.ini`:
```
[testenv]
commands =
    pytest --basetemp={envtmpdir} --cov=<your package>
    - codecov
```

**Comment by dmtucker** [comment]
> When having the issue with tox, I turned `usedevelop = True` and it fixed the issue.

This does not appear to work with an intermediate `src/` directory.

**Comment by ionelmc** [comment]
@dmtucker please open an issue and post some details to help reproduce your problem.

**Comment by geoff-coppertop** [comment]
More annoying than anything I see "Coverage.py warning: No data was collected. (no-data-collected)" in the command output when I run "make test" from the root of the following repo https://github.com/geoff-coppertop/python-hw-railroad

I'm still getting the coverage data in the reports directory.

**Comment by Midnighter** [comment]
For the source path I would define that with tox. I'm referring to [this line](https://github.com/geoff-coppertop/python-hw-railroad/blob/588c9630da897301678250cdabe6f92b901ed325/tox.ini#L19). I'd rather write in `testenv` section:

```ini
[testenv]
commands =
    pytest --cov={envsitepackagesdir}/hw_railroad
```

**Comment by geoff-coppertop** [comment]
@Midnighter I did that and it removes the warning, but the test time goes way up. If I remove the --cov that exists in [pytest] for "addopts" the test time is back to what it was before but the warning is back too. If I remove --cov from "addopts" then I start getting errors. From what I understand "addopts" should be equivalent to appending to the ending of the pytest command under the "commands" part of [testenv].

**Comment by Midnighter** [comment]
Yes, it should be equivalent but the `{envsitepackagesdir}` variable is tox specific. So I don't think you can use it anywhere else. I would expect coverage measurement to increase the testing time. Are you sure the coverage data that you get without this is actually correct?

**Comment by geoff-coppertop** [comment]
I am reasonably certain the coverage data is correct after looking at the reports in HTML. I have added a dummy function that is not tested and see the coverage decrease. I'll admit that part of me is probably being too picky but I'm worried the warning might mask something important later, I have three modules that are structured the same way.

**Comment by Juanlu001** [comment]
> To be honest I have never figured out how to get that damn mapping to work (https://coverage.readthedocs.org/en/latest/config.html#paths) so I always have two envs, one for normal runs and one for coverage runs (where something alone the lines of pip install -e . happens - editable installs).

I guess is the proper place to track how to do this right is https://github.com/pytest-dev/pytest-cov/issues/176?

**Comment by theRealSuperMario** [comment]
> @geoff-coppertop For the source path I would define that with tox. I'm referring to [this line](https://github.com/geoff-coppertop/python-hw-railroad/blob/588c9630da897301678250cdabe6f92b901ed325/tox.ini#L19). I'd rather write in `testenv` section:
> 
> ```ini
> [testenv]
> commands =
>     pytest --cov={envsitepackagesdir}/hw_railroad
> ```

that solved it for me

**Comment by rogerdahl** [comment]
I have an `omit =` section in my `.coveragerc` with around 20 filters. If I add a filter of `*/.*` to exclude dot-files and dot-dirs, I start getting the "Coverage.py warning: No data was collected" warnings.

```bash
omit =
  # All dot-files and dirs
  */.*
  ...
```

**Comment by Midnighter** [comment]
I have finished up a minimal Python package repo just yesterday. It demonstrates how to combine tox with an installed package from `src/` to get coverage and successful reports at codecov.io, too.

You can find the [full-implementation branch here](https://github.com/Midnighter/calculator-demo/tree/full-implementation).

In order to get codecov.io working, I had to configure the following section.

```ini
[coverage:paths]
source =
    src/demo
*/site-packages/demo
```

where `demo` is the name of the package.

**Comment by ionelmc** [comment]
@rogerdahl if Midnighter didn't address your problem already it would be best to open a new issue for your problem (with a reproducer and such).

**Comment by rogerdahl** [comment]
Thanks, @ionelmc. My issue is resolved. I just added it as a datapoint for others who might have this issue.

**Comment by bsergean** [comment]
I spent a long time troubleshooting that problem (on travis), and I fixed it by adding an __init__.py file in my tests directory. That was it ...

**Comment by ttruongatl** [comment]
adding `__init__.py` into `test` folder works fine for me.

**Comment by joaomcteixeira** [comment]
Just to add on the discussion:
I can have nice coverage report running mannually:
```
pytest --cov=src --cov-append --cov-report=term-missing --junitxml 1.xml tests/
```
but when in `tox` I had to add the
```
usedevelop = true
```
line to `[testenv]`. With this option the output was the same results as running manually.

It there any fault added to this strategy? For example, not testing a proper installation?

`tox.ini`:
```
[coverage:paths]                                                                
source =                                                                        
    src                                                                         
                                                                                
[coverage:run]                                                                  
branch = true                                                                   
source =                                                                        
    src                                                                         
parallel = true                                                                 
                                                                                
[coverage:report]                                                               
show_missing = true                                                             
precision = 2                                                                   
omit = *migrations*                                                             
                                                                                
# https://hypothesis.readthedocs.io/en/latest/index.html                        
[testenv]                                                                       
wheel = true                                                                    
usedevelop = true                                                               
passenv = *                                                                     
deps =                                                                          
    pytest                                                                      
    pytest-travis-fold                                                          
    pytest-cov                                                                  
    hypothesis                                                                  
commands =                                                                      
    pytest --cov --cov-append --cov-report=term-missing --junitxml {toxworkdir}/junit.{envname}.xml {posargs} tests/
```

**Comment by dmtucker** [comment]
> It there any fault added to this strategy?

Yes, it makes it slightly more likely that breaking the build/install would not be caught (because the package and its deps are not reinstalled for every Tox run).

**Comment by joaomcteixeira** [comment]
Hi @dmtucker 
Thanks for your reply, you indeed confirmed my suspicions (I am still new to Tox). After my comment, I went on reading more and I actually understood the strategy (and syntax) of @ionelmc [tox.ini at master branch](https://github.com/ionelmc/python-nameless/blob/master/tox.ini) config duplicating the tests with `userdevelop` `on` and `off`, I guess that's what he meant in his [comment above](https://github.com/pytest-dev/pytest-cov/issues/98#issuecomment-153918021).

Thanks for the explanation

**Comment by dm-wyncode** [comment]
I sometimes have this issue when I run `tox -p auto`. 
The py38 version outputs a warning "warning: No data was collected" yet there is no warning for py36 or py37. 

(I am new to tox and was looking for a solution which is what brought me here.)

Though it takes longer `tox -r -p auto` does not output the warning. Subsequent runs of `tox -p auto` then no longer output the warning.

 I probably have done something unconventional along the way.

**Comment by eric-wieser** [comment]
It turns out that the `[paths]` solution described above only works if you have multiple coverage runs you then combine. If you only have a single run, this seems to fix the problem:
```
mv .coverage .coverage.hack  # I can't combine it without renaming
coverage combine
coverage report
```

**Comment by chrisinmtown** [comment]
> I got the same issue and adding a tests/**init**.py helped. Refer to http://thomas-cokelaer.info/blog/2017/01/pytest-cov-collects-no-data-on-travis/

For newbies like me, just for clarity, please note this solution requires adding file tests/(underscore)(underscore)init(underscore)(underscore).py  aka `__init__.py` like any other package
